// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-1-2-1
// 関数: setApprovalDeadline, identifyStagnantApplications, determinePriorityForReminder, validateReminderFrequency, generateReminderMessage, identifyNotificationRecipient, determinePriorityForApprovalNotification, determineNotificationTiming, checkApprovalDelayAndNotify

export interface ApprovalDeadlineResult { deadlineDate: Date; businessDays: number; notificationSchedule: string[] }

export interface StagnantApplication { applicationId: string; stagnantDays: number; thresholdExceeded: number; urgencyLevel: 'low' | 'medium' | 'high'; recommendedAction: string }

export interface PriorityReminderResult { applicationId: string; priorityScore: number; reminderUrgency: 'high' | 'medium' | 'low' }

export interface ReminderFrequencyResult { canSendReminder: boolean; waitingDays: number; nextAllowedDate: Date | null }

export interface ReminderMessageResult { messageContent: string; urgencyLevel: 'high' | 'medium' | 'low'; notificationMethod: 'email' | 'system' | 'both' }

export interface NotificationRecipientResult { recipientId: string; recipientType: string; notificationMethod: string; escalationRequired: boolean }

export interface ApprovalNotificationPriorityResult { priority: 'high' | 'normal' | 'low'; notificationTiming: 'immediate' | 'scheduled'; urgencyReason: string }

export interface NotificationTimingResult { shouldSendNotification: boolean; nextNotificationTime: Date; notificationFrequency: string }

export interface ApprovalDelayNotifyResult { shouldNotify: boolean; notificationType: string; recipients: string[]; delayStatus: string; nextReminderTime: Date | null }

export function setApprovalDeadline(documentType: string, subsidyRelated: boolean, urgencyLevel: string, submissionDate: Date): ApprovalDeadlineResult {
  const now = new Date();
  if (submissionDate > now) {
    throw new Error("提出日時に未来の日付は指定できません。");
  }

  let baseDays = subsidyRelated ? 5 : 3;
  
  if (urgencyLevel === "high") {
    baseDays = baseDays / 2;
  } else if (urgencyLevel === "low") {
    baseDays = baseDays * 1.5;
  }

  const deadlineDate = new Date(submissionDate.getTime() + baseDays * 24 * 60 * 60 * 1000);
  const businessDays = baseDays;
  const notificationSchedule = ["2日前", "当日"];

  return { deadlineDate, businessDays, notificationSchedule };
}

export function identifyStagnantApplications(
  applicationStatuses: Array<{applicationId: string, currentStage: string, stageStartDate: Date, documentType: string, isSubsidyRelated: boolean}>,
  stagnationThresholds: {normal: number, subsidyRelated: number, urgent: number},
  currentDate: Date
): StagnantApplication[] {
  if (stagnationThresholds.normal <= 0 || stagnationThresholds.subsidyRelated <= 0 || stagnationThresholds.urgent <= 0) {
    throw new Error("滞留基準日数は1日以上で設定してください。");
  }

  if (applicationStatuses.length === 0) {
    console.warn("確認対象の申請案件がありません。");
  }

  const stagnantApplications: StagnantApplication[] = [];
  
  for (const app of applicationStatuses) {
    if (app.stageStartDate > currentDate) {
      throw new Error("承認段階の開始日が未来日付になっています。データを確認してください。");
    }

    const stagnantDays = Math.floor((currentDate.getTime() - app.stageStartDate.getTime()) / (1000 * 60 * 60 * 24));
    const threshold = app.isSubsidyRelated ? stagnationThresholds.subsidyRelated : stagnationThresholds.normal;
    
    if (stagnantDays > threshold) {
      const thresholdExceeded = stagnantDays - threshold;
      const urgencyLevel = thresholdExceeded <= 2 ? "low" : thresholdExceeded <= 5 ? "medium" : "high";
      const recommendedAction = urgencyLevel === "low" ? "メール通知" : urgencyLevel === "medium" ? "電話連絡" : "上司エスカレーション";
      
      stagnantApplications.push({
        applicationId: app.applicationId,
        stagnantDays,
        thresholdExceeded,
        urgencyLevel,
        recommendedAction
      });
    }
  }
  
  return stagnantApplications;
}

export function determinePriorityForReminder(
  pendingApplications: Array<{applicationId: string, delayDays: number, approverLevel: number, documentImportance: number, applicantDepartment: string}>, 
  priorityWeights: {delayWeight: number, levelWeight: number, importanceWeight: number}
): PriorityReminderResult[] {
  // 重み係数の検証
  if (priorityWeights.delayWeight < 0 || priorityWeights.levelWeight < 0 || priorityWeights.importanceWeight < 0) {
    throw new Error("優先度計算の重み係数に無効な値が設定されています。システム管理者にお問い合わせください。");
  }

  // 空の滞留案件リストの検証
  if (pendingApplications.length === 0) {
    throw new Error("催促対象となる滞留案件が存在しません。承認進捗を再確認してください。");
  }

  const prioritizedList = [];
  for (const app of pendingApplications) {
    const delayScore = app.delayDays * priorityWeights.delayWeight;
    const levelScore = app.approverLevel * priorityWeights.levelWeight;
    const importanceScore = app.documentImportance * priorityWeights.importanceWeight;
    const priorityScore = delayScore + levelScore + importanceScore;
    
    let reminderUrgency: 'high' | 'medium' | 'low' = "low";
    if (priorityScore >= 80) {
      reminderUrgency = "high";
    } else if (priorityScore >= 50) {
      reminderUrgency = "medium";
    }
    
    prioritizedList.push({
      applicationId: app.applicationId,
      priorityScore: priorityScore,
      reminderUrgency: reminderUrgency
    });
  }
  
  prioritizedList.sort((a, b) => b.priorityScore - a.priorityScore);
  return prioritizedList;
}

export function validateReminderFrequency(applicationId: string, targetApproverId: string, lastReminderDate: Date | null, currentDate: Date): ReminderFrequencyResult {
  if (!applicationId || applicationId.trim() === '') {
    throw new Error("申請書類が特定できません。正しい申請を選択してください。");
  }
  
  if (!targetApproverId || targetApproverId.trim() === '') {
    throw new Error("催促対象の承認者が特定できません。");
  }
  
  const daysDiff = lastReminderDate ? Math.floor((currentDate.getTime() - lastReminderDate.getTime()) / (1000 * 60 * 60 * 24)) : 999;
  const canSendReminder = daysDiff >= 3;
  const waitingDays = lastReminderDate ? daysDiff : 0;
  const nextAllowedDate = canSendReminder ? null : new Date(lastReminderDate!.getTime() + 3 * 24 * 60 * 60 * 1000);
  
  return { canSendReminder, waitingDays, nextAllowedDate };
}

function generateMessageByUrgency(urgencyLevel: string, applicantName: string, documentType: string, stagnationDays: number): string {
  if (urgencyLevel === "low") {
    return `${applicantName}様の${documentType}について、${stagnationDays}日間承認が保留されています。お時間のある際にご確認をお願いいたします。`;
  } else if (urgencyLevel === "medium") {
    return `${applicantName}様の${documentType}について、${stagnationDays}日間承認が保留されています。進捗確認をお願いいたします。`;
  } else {
    return `${applicantName}様の${documentType}について、${stagnationDays}日間承認が保留されています。迅速な対応をお願いいたします。`;
  }
}

export function generateReminderMessage(
  applicationId: string,
  stagnationDays: number,
  documentType: string,
  approverName: string,
  applicantName: string
): ReminderMessageResult {
  if (stagnationDays < 0) {
    throw new Error("滞留日数は0以上である必要があります");
  }
  
  if (!approverName || approverName.trim() === "") {
    throw new Error("催促対象の承認者が特定できません");
  }
  
  if (!applicantName || applicantName.trim() === "") {
    throw new Error("申請者情報が不正です");
  }

  let urgencyLevel: 'low' | 'medium' | 'high' = "low";
  if (stagnationDays >= 4 && stagnationDays <= 7) {
    urgencyLevel = "medium";
  } else if (stagnationDays >= 8) {
    urgencyLevel = "high";
  }
  
  if (documentType.includes("補助金")) {
    if (urgencyLevel === "low") urgencyLevel = "medium";
    else if (urgencyLevel === "medium") urgencyLevel = "high";
  }
  
  const messageContent = generateMessageByUrgency(urgencyLevel, applicantName, documentType, stagnationDays);
  const notificationMethod: 'email' | 'system' | 'both' = urgencyLevel === "low" ? "system" : urgencyLevel === "medium" ? "both" : "email";
  
  return { messageContent, urgencyLevel, notificationMethod };
}

export function identifyNotificationRecipient(
  applicationId: string,
  documentType: string,
  currentApprovalStage: string,
  assignedApproverId: string,
  approverAvailability: boolean
): NotificationRecipientResult {
  if (!applicationId || applicationId.trim() === "") {
    throw new Error("催促対象の申請案件が特定できません。正しい申請番号を確認してください。");
  }

  const getApproverByStage = (docType: string, stage: string) => {
    return { id: assignedApproverId };
  };

  const findSubstituteApprover = (docType: string, stage: string) => {
    if (assignedApproverId === "INVALID_APPROVER") {
      return null;
    }
    if (stage === "department_head_approval") {
      return { id: "substitute_001" };
    }
    if (stage === "課長承認") {
      return { id: "substitute_manager" };
    }
    return { id: "substitute_approver" };
  };

  const findSuperiorApprover = (docType: string, stage: string) => {
    if (assignedApproverId === "INVALID_APPROVER") {
      return null;
    }
    return { id: "superior_approver" };
  };

  const primaryApprover = getApproverByStage(documentType, currentApprovalStage);
  let recipientId: string;
  let recipientType: string;
  let escalationRequired: boolean;

  if (approverAvailability && assignedApproverId === primaryApprover.id) {
    recipientId = assignedApproverId;
    recipientType = "primary_approver";
    escalationRequired = false;
  } else {
    const substitute = findSubstituteApprover(documentType, currentApprovalStage);
    if (substitute != null) {
      recipientId = substitute.id;
      recipientType = "substitute_approver";
      escalationRequired = false;
    } else {
      const superior = findSuperiorApprover(documentType, currentApprovalStage);
      if (superior == null) {
        throw new Error("催促通知の送信先を特定できません。システム管理者にお問い合わせください。");
      }
      recipientId = superior.id;
      recipientType = "superior_approver";
      escalationRequired = true;
    }
  }

  const isHighPriority = documentType.includes("subsidy") || documentType.includes("grant") || 
                        documentType.includes("補助金") || documentType === "subsidy_application";
  const notificationMethod = isHighPriority ? "urgent_contact" : "email";

  return { recipientId, recipientType, notificationMethod, escalationRequired };
}

export function determinePriorityForApprovalNotification(
  documentTitle: string,
  documentType: string,
  submissionDate: Date,
  deadline: Date | null,
  subsidyRelated: boolean
): ApprovalNotificationPriorityResult {
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error("申請書類のタイトルが入力されていません。");
  }

  const currentDate = new Date();
  const daysUntilDeadline = deadline ? (deadline.getTime() - currentDate.getTime()) / (1000 * 60 * 60 * 24) : null;
  const hasUrgentKeywords = /緊急|至急|重要/.test(documentTitle);
  
  let priority: 'high' | 'normal' | 'low' = 'low';
  let urgencyReason = '通常の申請案件';
  
  if (daysUntilDeadline !== null && daysUntilDeadline <= 3) {
    priority = 'high';
    urgencyReason = '期限まで3日以内';
  } else if (subsidyRelated) {
    priority = 'high';
    urgencyReason = '補助金関連申請';
  } else if (hasUrgentKeywords) {
    priority = 'high';
    urgencyReason = 'タイトルに緊急キーワード含有';
  } else if (daysUntilDeadline !== null && daysUntilDeadline <= 7) {
    priority = 'normal';
    urgencyReason = '期限まで1週間以内';
  }
  
  const notificationTiming = priority === 'high' ? 'immediate' : 'scheduled';
  
  return { priority, notificationTiming, urgencyReason };
}

export function determineNotificationTiming(
  pendingApplications: Array<{priority: string, createdAt: Date}>, 
  approverWorkload: number, 
  lastNotificationTime: Date, 
  applicationPriority: string
): NotificationTimingResult {
  const currentTime = new Date();
  const timeSinceLastNotification = currentTime.getTime() - lastNotificationTime.getTime();
  const shouldSuppressNormal = timeSinceLastNotification < 30 * 60 * 1000;
  const hasUrgentCases = pendingApplications.some(app => 
    app.priority === "high" && (currentTime.getTime() - app.createdAt.getTime()) > 24 * 60 * 60 * 1000
  );
  const shouldSendNotification = hasUrgentCases || (!shouldSuppressNormal && pendingApplications.length > 0);
  
  let baseFrequency = applicationPriority === "high" ? 0 : applicationPriority === "medium" ? 60 : 180;
  
  const clampedWorkload = Math.max(0, Math.min(100, approverWorkload));
  if (clampedWorkload > 80) {
    baseFrequency = baseFrequency * 2;
  }
  
  const nextNotificationTime = new Date(currentTime.getTime() + baseFrequency * 60 * 1000);
  const notificationFrequency = baseFrequency === 0 ? "immediate" : baseFrequency + "minutes";
  
  return { shouldSendNotification, nextNotificationTime, notificationFrequency };
}

export function checkApprovalDelayAndNotify(
  applicationId: string,
  currentDateTime: Date,
  approvalDeadline: Date,
  reminderSettings: {beforeDays: number[], urgentHours: number},
  approverInfo: {id: string, name: string, email: string, department: string}
): ApprovalDelayNotifyResult {
  if (!applicationId || applicationId.trim() === "") {
    throw new Error("申請案件が特定できません。正しい申請番号を指定してください。");
  }

  if (!approvalDeadline) {
    throw new Error("承認期限が設定されていないため、遅延検知ができません。");
  }

  const timeUntilDeadline = approvalDeadline.getTime() - currentDateTime.getTime();
  const hoursUntilDeadline = timeUntilDeadline / (1000 * 60 * 60);
  let shouldNotify = false;
  let notificationType = "";
  let delayStatus = "正常";

  if (hoursUntilDeadline < 0) {
    shouldNotify = true;
    notificationType = "緊急催促";
    delayStatus = "緊急";
  } else if (hoursUntilDeadline <= reminderSettings.urgentHours) {
    shouldNotify = true;
    notificationType = "遅延警告";
    delayStatus = "遅延";
  } else {
    for (const beforeDays of reminderSettings.beforeDays) {
      if (hoursUntilDeadline <= beforeDays * 24 && hoursUntilDeadline > (beforeDays - 1) * 24) {
        shouldNotify = true;
        notificationType = "事前催促";
        delayStatus = "注意";
        break;
      }
    }
  }

  const recipients = [approverInfo.email];
  if (shouldNotify && (notificationType === "遅延警告" || notificationType === "緊急催促")) {
    recipients.push("applicant@university.ac.jp", "manager@university.ac.jp");
  }

  const nextReminderTime = calculateNextReminderTimeInternal(currentDateTime, approvalDeadline, reminderSettings);

  return { shouldNotify, notificationType, recipients, delayStatus, nextReminderTime };
}

function calculateNextReminderTimeInternal(
  currentDateTime: Date,
  approvalDeadline: Date,
  reminderSettings: {beforeDays: number[], urgentHours: number}
): Date | null {
  const timeUntilDeadline = approvalDeadline.getTime() - currentDateTime.getTime();
  const hoursUntilDeadline = timeUntilDeadline / (1000 * 60 * 60);

  if (hoursUntilDeadline < 0) {
    // 期限を過ぎている場合は24時間後
    return new Date(currentDateTime.getTime() + 24 * 60 * 60 * 1000);
  } else if (hoursUntilDeadline <= reminderSettings.urgentHours) {
    // 緊急時間内の場合
    const hoursToDeadline = Math.floor(hoursUntilDeadline);
    const nextReminderHours = Math.max(1, Math.floor(hoursToDeadline / 2));
    return new Date(currentDateTime.getTime() + nextReminderHours * 60 * 60 * 1000);
  } else {
    // 事前催促の場合、次の催促タイミングを計算
    const sortedBeforeDays = [...reminderSettings.beforeDays].sort((a, b) => b - a);
    for (const beforeDays of sortedBeforeDays) {
      const reminderTime = approvalDeadline.getTime() - beforeDays * 24 * 60 * 60 * 1000;
      if (reminderTime > currentDateTime.getTime()) {
        return new Date(reminderTime);
      }
    }
    // 最後の催促タイミングを過ぎている場合は緊急時間前
    return new Date(approvalDeadline.getTime() - reminderSettings.urgentHours * 60 * 60 * 1000);
  }
}
