// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-2-1-1
// 関数: validateApplicationInput, validateApplicationAmountAndPeriod, classifyDocumentTypeAndRoute, determineDocumentTypeAndRoute, checkMoeComplianceRequirements, determineDigitalizationEligibility, determineProcessingRoute, handleDocumentClassificationException, determineDocumentStorageMethod, determineDocumentAcceptanceEligibility, handleSystemFailureAlternativeProcess

export interface DocumentClassificationResult { documentType: string; processingRoute: string; subsidyRelated: boolean; paperStorageRequired: boolean; }

export interface ValidationResult { isValid: boolean; errors: string[]; warnings: string[]; }

export interface ExtendedDocumentResult { documentType: string; processingRoute: string; subsidyRelated: boolean; paperStorageRequired: boolean; isSubsidyRelated: boolean; requiresPaperStorage: boolean; }

export interface ProcessingRouteResult { documentType: string; processingRoute: string; subsidyRelated: boolean; paperStorageRequired: boolean; approvalFlow: string; }

export interface AcceptanceEligibilityResult { documentType: string; processingRoute: 'electronic' | 'hybrid'; subsidyRelated: boolean; paperStorageRequired: boolean; acceptanceEligible: boolean; }

export interface ExceptionHandlingResult { finalDocumentType: string; processingRoute: string; exceptionReason: string; learningData: { documentTitle: string; documentContent: string; finalDocumentType: string; exceptionReason: string; }; }

export interface ComplianceCheckResult { complianceStatus: string; paperStorageRequired: boolean; processingRoute: string; riskLevel: string; }

export interface SystemFailureResult { alternativeProcess: string; notificationTargets: string[]; dataRecoveryPlan: string; estimatedRecoveryTime: number; }

function isValidApplicationType(applicationType: string): boolean {
  const validTypes = ['補助金申請', '設備申請', '人事申請', '予算申請', '研究申請'];
  return validTypes.includes(applicationType);
}

function isValidDepartment(department: string): boolean {
  const validDepartments = ['理学部事務課', '工学部事務課', '学術研究推進部', '研究推進課', '総務部'];
  return validDepartments.includes(department);
}

function isValidUrgencyLevel(urgencyLevel: string): boolean {
  const validLevels = ['通常', '急ぎ', '至急'];
  return validLevels.includes(urgencyLevel);
}

export function validateApplicationInput(
  documentTitle: string,
  documentContent: string,
  applicationType: string,
  applicantDepartment: string,
  urgencyLevel: string
): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!documentTitle) {
    throw new Error("申請書類のタイトルは必須項目です。入力してください。");
  }

  if (documentTitle.length < 10 || documentTitle.length > 200) {
    throw new Error("申請書類のタイトルは必須項目です。入力してください。");
  }

  if (!documentContent) {
    throw new Error("申請内容は50文字以上で詳しく記載してください。");
  }

  if (documentContent.length < 50) {
    throw new Error("申請内容は50文字以上で詳しく記載してください。");
  }

  if (!applicationType) {
    throw new Error("申請種別を選択してください。");
  }

  if (!isValidApplicationType(applicationType)) {
    throw new Error("申請種別を選択してください。");
  }

  if (!applicantDepartment) {
    throw new Error("所属部署を入力してください。");
  }

  if (!isValidDepartment(applicantDepartment)) {
    throw new Error("所属部署を入力してください。");
  }

  if (!urgencyLevel || !isValidUrgencyLevel(urgencyLevel)) {
    errors.push("緊急度を選択してください");
  }

  const isValid = errors.length === 0;

  return { isValid, errors, warnings };
}

export function validateApplicationAmountAndPeriod(
  applicationAmount: number,
  implementationStartDate: string,
  implementationEndDate: string,
  documentType: string,
  budgetLimits: object
): { isAmountValid: boolean; isPeriodValid: boolean; validationErrors: string[]; canProceed: boolean; } {
  // 申請金額の妥当性チェック
  if (applicationAmount <= 0 || !Number.isFinite(applicationAmount)) {
    throw new Error("申請金額は正の数値で入力してください");
  }

  // 日付形式の妥当性チェック
  const startDate = new Date(implementationStartDate);
  const endDate = new Date(implementationEndDate);
  
  if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
    throw new Error("実施期間は有効な日付形式で入力してください");
  }

  const budgetLimit = (budgetLimits as any)[documentType];
  
  // 申請金額の範囲チェック
  const isAmountValid = budgetLimit && 
    applicationAmount >= budgetLimit.minAmount && 
    applicationAmount <= budgetLimit.maxAmount;

  // 実施期間の妥当性チェック
  const today = new Date();
  today.setHours(0, 0, 0, 0); // 時刻をリセットして日付のみで比較
  const isPeriodValid = startDate >= today && endDate > startDate;

  // エラーメッセージの生成
  const validationErrors: string[] = [];
  
  if (!isAmountValid) {
    validationErrors.push("申請金額が規定範囲外です");
  }
  
  if (!isPeriodValid) {
    validationErrors.push("実施期間が不正です");
  }

  // 予算上限の150%超過チェック（警告）
  if (budgetLimit && applicationAmount > budgetLimit.maxAmount * 1.5) {
    console.warn("申請金額が大幅に予算上限を超過しています。金額を見直してください");
  }

  const canProceed = isAmountValid && isPeriodValid;

  return {
    isAmountValid,
    isPeriodValid,
    validationErrors,
    canProceed
  };
}

function calculateSubsidyKeywordMatch(title: string, content: string): number {
  const subsidyKeywords = [
    '科研費', '科学研究費', '補助金', '運営費交付金', '設備整備費',
    '研究費', '助成金', '交付金', '文部科学省', '研究機器',
    '研究設備', '研究環境', '研究推進'
  ];
  
  const text = (title + ' ' + content).toLowerCase();
  const totalWords = text.split(/\s+/).length;
  let matchCount = 0;
  
  subsidyKeywords.forEach(keyword => {
    const regex = new RegExp(keyword, 'gi');
    const matches = text.match(regex);
    if (matches) {
      matchCount += matches.length;
    }
  });
  
  return totalWords > 0 ? matchCount / totalWords : 0;
}

function determineDocumentTypeInternal(title: string, department: string): string {
  const subsidyKeywords = ['科研費', '補助金', '交付金', '研究費'];
  const hasSubsidyKeyword = subsidyKeywords.some(keyword => title.includes(keyword));
  
  if (hasSubsidyKeyword) {
    return '補助金申請';
  }
  
  return '一般申請';
}

function isMoeRequiredPaperStorageInternal(documentType: string): boolean {
  return documentType === '補助金申請';
}

export function classifyDocumentTypeAndRoute(
  documentTitle: string,
  documentContent: string,
  applicantDepartment: string
): DocumentClassificationResult {
  if (!documentTitle || documentTitle.length < 10) {
    throw new Error("申請書類のタイトルは10文字以上で入力してください");
  }
  
  if (!documentContent || documentContent.length < 50) {
    throw new Error("申請書類の内容は50文字以上で入力してください");
  }
  
  if (!applicantDepartment) {
    throw new Error("所属部署を選択してください");
  }
  
  const keywordScore = calculateSubsidyKeywordMatch(documentTitle, documentContent);
  const subsidyRelated = keywordScore >= 0.7;
  const documentType = determineDocumentTypeInternal(documentTitle, applicantDepartment);
  const paperStorageRequired = subsidyRelated && isMoeRequiredPaperStorageInternal(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  
  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired
  };
}

function calculateSubsidyKeywordScore(title: string, content: string): number {
  const subsidyKeywords = [
    '科研費', '科学研究費', '運営費交付金', '補助金', '助成金', 
    '設備整備費', '文部科学省', '研究費', '交付金', '基盤研究',
    '挑戦的研究', '若手研究', '特別研究員奨励費'
  ];
  
  const text = (title + ' ' + content).toLowerCase();
  const totalWords = text.split(/\s+/).length;
  let matchCount = 0;
  
  subsidyKeywords.forEach(keyword => {
    const regex = new RegExp(keyword, 'gi');
    const matches = text.match(regex);
    if (matches) {
      matchCount += matches.length;
    }
  });
  
  return Math.min(matchCount / Math.max(totalWords * 0.1, 1), 1.0);
}

function isResearchDepartment(department: string): boolean {
  const researchDepts = ['研究科', '理学部', '工学部', '医学部', '研究推進課', '研究室'];
  return researchDepts.some(dept => department.includes(dept));
}

function requiresPaperStorageForMoe(documentType: string, title: string): boolean {
  const moeRequiredTypes = ['補助金申請', '補助金申請書'];
  const moeKeywords = ['文部科学省', '科研費', '運営費交付金'];
  
  if (!moeRequiredTypes.includes(documentType)) {
    return false;
  }
  
  return moeKeywords.some(keyword => title.includes(keyword));
}

function classifyDocumentTypeInternal(title: string, content: string, isSubsidy: boolean, department: string): string {
  if (isSubsidy) {
    if (title.includes('申請書')) {
      return '補助金申請書';
    }
    return '補助金申請';
  }
  
  if (isResearchDepartment(department) && (title.includes('研究') || content.includes('研究'))) {
    return '研究関連書類';
  }
  
  if (title.includes('申請書')) {
    return '一般申請書';
  }
  
  return '一般申請';
}

export function determineDocumentTypeAndRoute(
  documentTitle: string, 
  documentContent: string, 
  applicantDepartment: string
): ExtendedDocumentResult {
  // 制約チェック
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error('申請書類のタイトルを入力してください');
  }
  
  if (!documentContent || documentContent.trim() === '') {
    throw new Error('申請書類の内容は10文字以上で入力してください');
  }
  
  if (documentContent.length < 10) {
    throw new Error('申請内容が短すぎる可能性があります。内容を確認してください');
  }
  
  if (!applicantDepartment || applicantDepartment.trim() === '') {
    throw new Error('申請者の所属部署を選択してください');
  }
  
  // 補助金関連度計算
  const keywordScore = calculateSubsidyKeywordScore(documentTitle, documentContent);
  const isResearchDept = isResearchDepartment(applicantDepartment);
  const threshold = isResearchDept ? 0.6 : 0.7;
  const subsidyRelated = keywordScore >= threshold;
  
  // 文書種別判定
  const documentType = classifyDocumentTypeInternal(documentTitle, documentContent, subsidyRelated, applicantDepartment);
  
  // 紙保管要否判定
  const paperStorageRequired = subsidyRelated && requiresPaperStorageForMoe(documentType, documentTitle);
  
  // 処理ルート決定
  const processingRoute = paperStorageRequired ? 'hybrid' : 'electronic';
  
  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired,
    isSubsidyRelated: subsidyRelated,
    requiresPaperStorage: paperStorageRequired
  };
}

function calculateMoeKeywordMatch(title: string, content: string, keywords: string[]): number {
  const text = (title + ' ' + content).toLowerCase();
  const matchedKeywords = keywords.filter(keyword => 
    text.includes(keyword.toLowerCase())
  );
  return matchedKeywords.length / keywords.length;
}

function checkMoeRequirementMatch(documentType: string, keywords: string[]): boolean {
  const subsidyRelatedTypes = ['補助金申請書', '設備導入申請書', '研究関連書類'];
  return subsidyRelatedTypes.some(type => 
    documentType.toLowerCase().includes(type.toLowerCase())
  );
}

export function checkMoeComplianceRequirements(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  subsidyKeywords: string[]
): ComplianceCheckResult {
  // バリデーション
  if (!documentTitle) {
    throw new Error("申請書類のタイトルが入力されていません。法令要件の判定ができません。");
  }
  
  if (documentTitle.length < 10) {
    throw new Error("申請書類のタイトルは10文字以上で入力してください");
  }
  
  if (!documentContent || documentContent.length < 50) {
    throw new Error("申請書類の内容は50文字以上で入力してください");
  }
  
  if (!documentType) {
    throw new Error("書類種別の分類が完了していません。先に文書種別の確認を行ってください。");
  }

  // キーワードマッチング計算
  const keywordScore = calculateMoeKeywordMatch(documentTitle, documentContent, subsidyKeywords);
  
  // 補助金関連判定
  const isSubsidyRelated = keywordScore >= 0.6;
  
  // 紙保管要件判定
  const paperStorageRequired = isSubsidyRelated && checkMoeRequirementMatch(documentType, subsidyKeywords);
  
  // 処理ルート決定
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  
  // コンプライアンス状況判定
  const complianceStatus = paperStorageRequired ? "compliant" : "review_required";
  
  // リスクレベル評価
  let riskLevel: string;
  if (keywordScore >= 0.8) {
    riskLevel = "high";
  } else if (keywordScore >= 0.4) {
    riskLevel = "medium";
  } else {
    riskLevel = "low";
  }

  return {
    complianceStatus,
    paperStorageRequired,
    processingRoute,
    riskLevel
  };
}

export function determineDigitalizationEligibility(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  subsidyRelevanceScore: number
): DocumentClassificationResult {
  if (!documentTitle || documentTitle.trim() === "") {
    throw new Error("申請書類のタイトルが入力されていません。タイトルを入力してください。");
  }

  if (subsidyRelevanceScore < 0 || subsidyRelevanceScore > 1) {
    throw new Error("補助金関連度の評価に異常があります。システム管理者にお問い合わせください。");
  }

  if (documentType === "未分類") {
    console.warn("文書種別の分類が完了していません。手動で種別を確認してください。");
  }

  const subsidyRelated = subsidyRelevanceScore >= 0.7;
  const moeRequiredTypes = ["補助金申請書", "事業報告書", "会計報告書", "監査資料"];
  const paperStorageRequired = subsidyRelated && moeRequiredTypes.includes(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";

  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired
  };
}

export function determineProcessingRoute(
  documentType: string,
  subsidyRelatedScore: number,
  documentTitle: string,
  documentContent: string
): ProcessingRouteResult {
  // 制約チェック
  if (!documentTitle || documentTitle.trim() === "") {
    throw new Error("申請書類のタイトルを入力してください");
  }
  
  if (subsidyRelatedScore < 0 || subsidyRelatedScore > 1) {
    throw new Error("補助金関連度の評価に異常があります。システム管理者にお問い合わせください");
  }
  
  // 警告ケース: 文書種別が未分類
  if (documentType === "未分類") {
    console.warn("文書種別を再確認してください。不明な場合は事務局にお問い合わせください");
  }
  
  // 業務ロジック実装
  const subsidyRelated = subsidyRelatedScore >= 0.7;
  const moeRequiredTypes = ["補助金申請書", "研究費申請書", "設備導入申請書"];
  const paperStorageRequired = subsidyRelated && moeRequiredTypes.includes(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  const approvalFlow = paperStorageRequired ? "special" : "standard";
  
  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired,
    approvalFlow
  };
}

function determineProcessingRouteInternal(documentType: string): string {
  // 補助金関連の文書種別はハイブリッド処理、その他は電子処理
  const subsidyRelatedTypes = ['補助金申請', '助成金申請', '研究費申請'];
  return subsidyRelatedTypes.includes(documentType) ? 'hybrid' : 'electronic';
}

function generateExceptionReasonInternal(autoClassificationResult: string | null, staffObjection: string | null): string {
  if (autoClassificationResult === null && staffObjection !== null) {
    return '職員からの異議により手動判定に移行';
  } else if (autoClassificationResult === null) {
    return '自動分類が失敗したため手動判定に移行';
  } else if (staffObjection !== null) {
    return '職員からの異議により手動判定に移行';
  }
  return '例外処理により手動判定に移行';
}

function createLearningDataInternal(
  documentTitle: string,
  documentContent: string,
  finalDocumentType: string,
  exceptionReason: string
) {
  return {
    documentTitle,
    documentContent,
    finalDocumentType,
    exceptionReason
  };
}

export function handleDocumentClassificationException(
  documentTitle: string,
  documentContent: string,
  autoClassificationResult: string | null,
  staffObjection: string | null,
  managerDecision: string
): ExceptionHandlingResult {
  if (!managerDecision || managerDecision.trim() === '') {
    throw new Error('例外処理には事務局長による最終判定が必要です');
  }

  if (autoClassificationResult === null || staffObjection !== null) {
    const finalDocumentType = managerDecision;
    const processingRoute = determineProcessingRouteInternal(finalDocumentType);
    const exceptionReason = generateExceptionReasonInternal(autoClassificationResult, staffObjection);
    const learningData = createLearningDataInternal(documentTitle, documentContent, finalDocumentType, exceptionReason);
    
    return {
      finalDocumentType,
      processingRoute,
      exceptionReason,
      learningData
    };
  }

  // 通常ケース（例外処理が不要な場合）
  const finalDocumentType = managerDecision;
  const processingRoute = determineProcessingRouteInternal(finalDocumentType);
  const exceptionReason = '例外処理により手動判定に移行';
  const learningData = createLearningDataInternal(documentTitle, documentContent, finalDocumentType, exceptionReason);

  return {
    finalDocumentType,
    processingRoute,
    exceptionReason,
    learningData
  };
}

function computeKeywordMatch(documentTitle: string, documentContent: string, subsidyKeywords: string[]): number {
  if (subsidyKeywords.length === 0) return 0;
  
  const combinedText = (documentTitle + ' ' + documentContent).toLowerCase();
  const matchedKeywords = subsidyKeywords.filter(keyword => 
    combinedText.includes(keyword.toLowerCase())
  );
  
  return matchedKeywords.length / subsidyKeywords.length;
}

function isMoeRequirement(documentType: string): boolean {
  const moeTypes = ['補助金申請書', '事業報告書'];
  return moeTypes.includes(documentType);
}

export function determineDocumentStorageMethod(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  subsidyKeywords: string[]
): DocumentClassificationResult {
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error('申請書類のタイトルが入力されていません。タイトルを入力してください。');
  }
  
  if (documentContent.length < 10) {
    console.warn('申請内容が短すぎる可能性があります。内容を確認してください。');
  }
  
  const score = computeKeywordMatch(documentTitle, documentContent, subsidyKeywords);
  const subsidyRelated = score >= 0.7;
  const paperStorageRequired = subsidyRelated && isMoeRequirement(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  
  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired
  };
}



export function determineDocumentAcceptanceEligibility(
  documentTitle: string,
  documentContent: string,
  documentType: string
): AcceptanceEligibilityResult {
  if (!documentTitle) {
    throw new Error("申請書類のタイトルを入力してください");
  }
  
  if (documentContent.length < 10) {
    throw new Error("申請書類の内容は10文字以上で入力してください");
  }
  
  if (!documentType) {
    throw new Error("文書種別を選択してください");
  }

  const subsidyKeywords = ["補助金", "助成金", "文部科学省", "科研費", "運営費交付金"];
  const score = computeKeywordMatch(documentTitle, documentContent, subsidyKeywords);
  const subsidyRelated = score >= 0.7;
  const moeRequirementTypes = ["補助金申請書", "実績報告書", "収支決算書"];
  const paperStorageRequired = subsidyRelated && moeRequirementTypes.includes(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  const acceptanceEligible = subsidyRelated;
  
  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired,
    acceptanceEligible
  };
}

function calculateRecoveryTime(failureType: string): number {
  switch (failureType) {
    case "system_crash":
      return 240;
    case "network_issue":
      return 60;
    case "database_error":
      return 120;
    case "server_overload":
      return 90;
    default:
      return 180;
  }
}

export function handleSystemFailureAlternativeProcess(
  systemStatus: string,
  failureType: string,
  documentType: string,
  urgencyLevel: number
): SystemFailureResult {
  if (!systemStatus) {
    throw new Error("システム状況を確認できません。情報システム課に連絡してください。");
  }

  if (!failureType) {
    console.warn("障害の詳細が不明です。標準的な代替処理を開始します。");
  }

  // 緊急度レベルの範囲チェック
  const clampedUrgencyLevel = Math.max(1, Math.min(10, urgencyLevel));
  if (urgencyLevel < 1 || urgencyLevel > 10) {
    console.warn("緊急度は1から10の範囲で指定してください。");
  }

  let alternativeProcess: string;
  if (systemStatus === "critical_failure") {
    alternativeProcess = "full_paper_mode";
  } else if (systemStatus === "partial_failure") {
    alternativeProcess = "manual_hybrid_mode";
  } else {
    alternativeProcess = "temporary_workaround";
  }

  let notificationTargets: string[];
  if (clampedUrgencyLevel >= 8) {
    notificationTargets = ["all_staff", "management", "it_support"];
  } else {
    notificationTargets = ["relevant_staff", "it_support"];
  }

  const dataRecoveryPlan = "sync_paper_to_electronic_after_recovery";
  const estimatedRecoveryTime = calculateRecoveryTime(failureType);

  return {
    alternativeProcess,
    notificationTargets,
    dataRecoveryPlan,
    estimatedRecoveryTime
  };
}
