// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-2-2-1
// 関数: validateApplicationInput, validateApplicationAmountAndPeriod, determineApprovalHierarchy, determineApprovalAuthority, determineApprovalDecision, determineNextApprover, setApproverAuthorityLevel, handleSystemFailureAlternativeProcess

export interface ValidationResult { isValid: boolean; errors: string[]; warnings: string[] }

export interface AmountPeriodValidationResult { isAmountValid: boolean; isPeriodValid: boolean; validationErrors: string[]; canProceed: boolean }

export interface ApprovalHierarchyResult { approvalLevel: string; approvers: string[]; estimatedDays: number; requiresPaperApproval: boolean }

export interface ApprovalAuthorityResult { hasAuthority: boolean; requiredPosition: string; nextApprover: string | null; processingRoute: string }

export interface ApprovalDecisionResult { decision: string; reason: string; conditionalRequirements: string[]; nextAction: string }

export interface NextApproverResult { nextApprover: string | null; processingRoute: string; isSubsidyRelated: boolean; requiresPaperStorage: boolean }

export interface ApproverAuthorityLevelResult { requiredAuthorityLevel: string; approverRoles: string[]; escalationRequired: boolean }

export interface SystemFailureResult { alternativeProcess: string; notificationTargets: string[]; dataRecoveryPlan: string; estimatedRecoveryTime: number }

export interface BudgetLimits { [documentType: string]: { minAmount: number; maxAmount: number } }

function isValidApplicationType(applicationType: string): boolean {
  const validTypes = ['補助金申請', '設備申請', '人事申請', '予算申請', '研修申請', '出張申請', '契約申請'];
  return validTypes.includes(applicationType);
}

function isValidDepartment(department: string): boolean {
  const validDepartments = ['研究推進課', '総務課', '経理課', '人事課', '企画課', '営業課', '開発課', '製造課'];
  return validDepartments.includes(department);
}

function isValidUrgencyLevel(urgencyLevel: string): boolean {
  const validLevels = ['通常', '急ぎ', '至急', '高', '中', '低'];
  return validLevels.includes(urgencyLevel);
}

export function validateApplicationInput(
  documentTitle: string,
  documentContent: string,
  applicationType: string,
  applicantDepartment: string,
  urgencyLevel: string
): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  
  if (!documentTitle || documentTitle.length < 10 || documentTitle.length > 200) {
    errors.push("申請書類のタイトルは10文字以上200文字以内で入力してください");
  }
  
  if (!documentContent || documentContent.length < 50) {
    errors.push("申請内容は50文字以上で詳しく記載してください");
  }
  
  if (!applicationType || !isValidApplicationType(applicationType)) {
    errors.push("申請種別を正しく選択してください");
  }
  
  if (!applicantDepartment || !isValidDepartment(applicantDepartment)) {
    errors.push("所属部署を正しく入力してください");
  }
  
  if (!urgencyLevel || !isValidUrgencyLevel(urgencyLevel)) {
    errors.push("緊急度を選択してください");
  }
  
  const isValid = errors.length === 0;
  
  return { isValid, errors, warnings };
}

export function validateApplicationAmountAndPeriod(
  applicationAmount: number,
  implementationStartDate: string,
  implementationEndDate: string,
  documentType: string,
  budgetLimits: BudgetLimits
): AmountPeriodValidationResult {
  // 申請金額の基本検証
  if (applicationAmount <= 0) {
    throw new Error("申請金額は正の数値で入力してください");
  }

  // 日付形式の検証
  const startDate = new Date(implementationStartDate);
  const endDate = new Date(implementationEndDate);
  
  if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
    throw new Error("実施期間は有効な日付形式で入力してください");
  }

  // 予算制限の取得
  const budgetLimit = budgetLimits[documentType];
  if (!budgetLimit) {
    throw new Error("指定された文書種別の予算制限が見つかりません");
  }

  // 150%超過チェック（例外をスロー）
  if (applicationAmount > budgetLimit.maxAmount * 1.5) {
    throw new Error("申請金額が大幅に予算上限を超過しています。金額を見直してください");
  }

  // 申請金額の妥当性チェック
  const isAmountValid = applicationAmount >= budgetLimit.minAmount && applicationAmount <= budgetLimit.maxAmount;

  // 実施期間の妥当性チェック
  const today = new Date();
  today.setHours(0, 0, 0, 0); // 時間部分をリセットして日付のみで比較
  startDate.setHours(0, 0, 0, 0);
  endDate.setHours(0, 0, 0, 0);
  
  const isPeriodValid = startDate >= today && endDate > startDate;

  // エラーメッセージの生成
  const validationErrors: string[] = [];
  if (!isAmountValid) {
    validationErrors.push("申請金額が規定範囲外です");
  }
  if (!isPeriodValid) {
    validationErrors.push("実施期間が不正です");
  }

  // 承認可能かどうかの判定
  const canProceed = isAmountValid && isPeriodValid;

  return {
    isAmountValid,
    isPeriodValid,
    validationErrors,
    canProceed
  };
}

function getApproversByLevel(approvalLevel: string, applicantDepartment: string): string[] {
  if (approvalLevel === "課長承認") {
    return ["課長"];
  } else if (approvalLevel === "部長承認") {
    return ["部長"];
  } else if (approvalLevel === "理事承認") {
    return ["理事"];
  }
  return [];
}

function getApproversForHighestLevel(approvalLevel: string, applicantDepartment: string): string[] {
  if (approvalLevel === "理事承認") {
    return ["課長", "部長", "理事"];
  }
  return getApproversByLevel(approvalLevel, applicantDepartment);
}

export function determineApprovalHierarchy(
  applicationAmount: number,
  documentType: string,
  applicantDepartment: string
): ApprovalHierarchyResult {
  // 制約チェック
  if (applicationAmount <= 0) {
    throw new Error("申請金額は1円以上で入力してください");
  }
  
  if (!applicantDepartment || applicantDepartment.trim() === "") {
    throw new Error("承認ルート設定のため、所属部署を入力してください");
  }

  // 1億円超過の警告（処理は続行）
  if (applicationAmount > 100000000) {
    console.warn("高額申請のため、理事会での特別承認が必要になる可能性があります");
  }

  let approvalLevel = "";
  let estimatedDays = 0;
  let requiresPaperApproval = false;
  
  if (documentType.includes("補助金")) {
    if (applicationAmount >= 1000000) {
      approvalLevel = "理事承認";
      estimatedDays = 7;
    } else {
      approvalLevel = "部長承認";
      estimatedDays = 5;
    }
    requiresPaperApproval = true;
  } else {
    if (applicationAmount < 100000) {
      approvalLevel = "課長承認";
      estimatedDays = 3;
    } else if (applicationAmount < 1000000) {
      approvalLevel = "部長承認";
      estimatedDays = 5;
    } else {
      approvalLevel = "理事承認";
      estimatedDays = 7;
    }
  }
  
  // 最高額（1億円）の場合は全階層の承認者を返す
  const approvers = applicationAmount >= 100000000 
    ? getApproversForHighestLevel(approvalLevel, applicantDepartment)
    : getApproversByLevel(approvalLevel, applicantDepartment);
    
  return { approvalLevel, approvers, estimatedDays, requiresPaperApproval };
}

function determineRequiredPosition(applicationType: string, applicationAmount: number): string {
  if (applicationType === "補助金申請") {
    if (applicationAmount >= 2000000) {
      return "理事";
    } else if (applicationAmount >= 500000) {
      return "部長";
    } else {
      return "課長";
    }
  }
  
  if (applicationAmount >= 1000000) {
    return "部長";
  } else {
    return "課長";
  }
}

function checkAuthorityLevel(approverPosition: string, requiredPosition: string): boolean {
  const positionHierarchy = ["課長", "部長", "理事"];
  const approverLevel = positionHierarchy.indexOf(approverPosition);
  const requiredLevel = positionHierarchy.indexOf(requiredPosition);
  
  return approverLevel >= requiredLevel;
}

function findNextApprover(requiredPosition: string): string {
  if (requiredPosition === "理事") {
    return "理事";
  } else if (requiredPosition === "部長") {
    return "部長";
  } else {
    return "課長";
  }
}

export function determineApprovalAuthority(
  approverPosition: string,
  applicationAmount: number,
  applicationType: string,
  approvalAction: string
): ApprovalAuthorityResult {
  if (!approverPosition || approverPosition.trim() === "") {
    throw new Error("承認者の職位情報を確認できません。システム管理者にお問い合わせください。");
  }
  
  if (applicationAmount < 0) {
    throw new Error("申請金額に正しい値を入力してください。");
  }
  
  if (!applicationType || applicationType.trim() === "") {
    throw new Error("申請種別を選択してください。");
  }
  
  const requiredPosition = determineRequiredPosition(applicationType, applicationAmount);
  const hasAuthority = checkAuthorityLevel(approverPosition, requiredPosition);
  
  if (!hasAuthority) {
    const nextApprover = findNextApprover(requiredPosition);
    return { hasAuthority: false, requiredPosition, nextApprover, processingRoute: "escalate" };
  }
  
  const processingRoute = approvalAction === "approve" ? "approved" : approvalAction === "reject" ? "rejected" : "returned";
  return { hasAuthority: true, requiredPosition, nextApprover: null, processingRoute };
}

function calculateDeficiencySeverity(deficiencyItems: string[]): number {
  if (deficiencyItems.length === 0) return 0;
  
  let maxSeverity = 0;
  for (const item of deficiencyItems) {
    const lowerItem = item.toLowerCase();
    if (lowerItem.includes('必要書類') || lowerItem.includes('添付漏れ') || lowerItem.includes('金額') || lowerItem.includes('記載ミス')) {
      maxSeverity = Math.max(maxSeverity, 8);
    } else if (lowerItem.includes('期間設定') || lowerItem.includes('誤り')) {
      maxSeverity = Math.max(maxSeverity, 7);
    } else if (lowerItem.includes('重大')) {
      maxSeverity = Math.max(maxSeverity, 9);
    } else if (lowerItem.includes('軽微')) {
      maxSeverity = Math.max(maxSeverity, 3);
    } else {
      maxSeverity = Math.max(maxSeverity, 5);
    }
  }
  return maxSeverity;
}

function generateConditionalRequirements(deficiencyItems: string[]): string[] {
  return deficiencyItems.map(item => `${item}の修正対応`);
}

export function determineApprovalDecision(
  documentContent: string,
  deficiencyItems: string[],
  subsidyRelated: boolean,
  urgencyLevel: number
): ApprovalDecisionResult {
  if (documentContent === "") {
    throw new Error("申請書類の内容が入力されていません。承認判定を行うことができません。");
  }

  if (urgencyLevel < 1 || urgencyLevel > 5) {
    console.warn("緊急度は1から5の範囲で入力してください。");
  }

  if (deficiencyItems.length === 0) {
    console.warn("不備項目が入力されていません。承認判定を行うには不備の有無を確認してください。");
  }

  const severityScore = calculateDeficiencySeverity(deficiencyItems);
  const deficiencyCount = deficiencyItems.length;

  if (subsidyRelated && severityScore >= 7) {
    return {
      decision: "reject",
      reason: "補助金関連書類で重要な不備があるため",
      conditionalRequirements: [],
      nextAction: "resubmit"
    };
  }

  if (deficiencyCount >= 3 || severityScore >= 8) {
    return {
      decision: "reject",
      reason: "重大な不備が複数あるため",
      conditionalRequirements: [],
      nextAction: "resubmit"
    };
  }

  if (deficiencyCount >= 1 && urgencyLevel >= 4) {
    const requirements = generateConditionalRequirements(deficiencyItems);
    return {
      decision: "conditional",
      reason: "軽微な不備があるが緊急性を考慮",
      conditionalRequirements: requirements,
      nextAction: "fulfill_conditions"
    };
  }

  return {
    decision: "approve",
    reason: "不備なしまたは軽微な不備のみ",
    conditionalRequirements: [],
    nextAction: "proceed"
  };
}

function analyzeSubsidyKeywords(title: string, content: string): number {
  const subsidyKeywords = [
    '補助金', '科研費', '科学研究費', '運営費交付金', '設備整備費', 
    '文部科学省', '基盤研究', '研究費', '交付金', '助成金'
  ];
  
  const text = (title + ' ' + content).toLowerCase();
  const totalWords = text.split(/\s+/).length;
  let matchCount = 0;
  
  subsidyKeywords.forEach(keyword => {
    const regex = new RegExp(keyword, 'gi');
    const matches = text.match(regex);
    if (matches) {
      matchCount += matches.length;
    }
  });
  
  return totalWords > 0 ? matchCount / totalWords : 0;
}

function checkMoeRequirements(title: string): boolean {
  const moeKeywords = ['文部科学省', '科研費', '科学研究費', '運営費交付金'];
  return moeKeywords.some(keyword => title.includes(keyword));
}

function determineNextApproverByRole(currentRole: string, isSubsidyRelated: boolean, decision: string): string | null {
  if (decision === '差戻し' || decision === '却下') {
    return null;
  }
  
  if (decision === '承認' || decision === 'approve') {
    const hierarchy = ['係長', '課長', '部長', '理事'];
    const currentIndex = hierarchy.indexOf(currentRole);
    
    if (currentIndex >= 0 && currentIndex < hierarchy.length - 1) {
      return hierarchy[currentIndex + 1];
    }
  }
  
  return null;
}

export function determineNextApprover(
  documentTitle: string,
  documentContent: string,
  currentApproverRole: string,
  approvalDecision: string
): NextApproverResult {
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error('申請書類のタイトルが入力されていません。タイトルを入力してください。');
  }
  
  if (!approvalDecision || approvalDecision.trim() === '') {
    throw new Error('承認・差戻し・却下のいずれかを選択してください。');
  }
  
  if (!currentApproverRole || currentApproverRole.trim() === '') {
    throw new Error('承認者の役職情報が取得できません。システム管理者にお問い合わせください。');
  }
  
  const keywordScore = analyzeSubsidyKeywords(documentTitle, documentContent);
  const isSubsidyRelated = keywordScore >= 0.7;
  const requiresPaperStorage = isSubsidyRelated && checkMoeRequirements(documentTitle);
  const processingRoute = requiresPaperStorage ? "hybrid" : "electronic";
  const nextApprover = determineNextApproverByRole(currentApproverRole, isSubsidyRelated, approvalDecision);
  
  return { nextApprover, processingRoute, isSubsidyRelated, requiresPaperStorage };
}

export function setApproverAuthorityLevel(
  documentType: string,
  subsidyRelated: boolean,
  paperStorageRequired: boolean,
  applicantDepartment: string,
  budgetAmount: number
): ApproverAuthorityLevelResult {
  // バリデーション
  if (budgetAmount < 0) {
    throw new Error("予算金額は0以上の値を入力してください");
  }
  
  if (applicantDepartment === "") {
    throw new Error("申請者の所属部署を選択してください");
  }

  // 業務ロジック
  const isHighBudget = budgetAmount > 5000000;
  const isVeryHighBudget = budgetAmount > 10000000;
  const needsHighAuthority = subsidyRelated || isHighBudget;
  
  const requiredAuthorityLevel = needsHighAuthority ? "department_head" : "section_chief";
  const approverRoles = [requiredAuthorityLevel];
  
  if (paperStorageRequired) {
    approverRoles.push("administrative_director");
  }
  
  const escalationRequired = isVeryHighBudget;
  
  return { requiredAuthorityLevel, approverRoles, escalationRequired };
}

function calculateRecoveryTime(failureType: string): number {
  switch (failureType) {
    case "approval_route_determination_error":
      return 240;
    case "database_error":
      return 120;
    case "network_error":
      return 60;
    case "authentication_error":
      return 30;
    default:
      return 180;
  }
}

export function handleSystemFailureAlternativeProcess(
  systemStatus: string,
  failureType: string,
  documentType: string,
  urgencyLevel: number
): SystemFailureResult {
  if (!systemStatus) {
    throw new Error("システム状況を確認できません。情報システム課に連絡してください。");
  }

  if (!failureType) {
    console.warn("障害の詳細が不明です。標準的な代替処理を開始します。");
  }

  if (urgencyLevel < 1 || urgencyLevel > 10) {
    console.warn("緊急度は1から10の範囲で指定してください。");
    urgencyLevel = Math.max(1, Math.min(10, urgencyLevel));
  }

  let alternativeProcess: string;
  if (systemStatus === "critical_failure") {
    alternativeProcess = "full_paper_mode";
  } else if (systemStatus === "partial_failure") {
    alternativeProcess = "manual_hybrid_mode";
  } else {
    alternativeProcess = "temporary_workaround";
  }

  let notificationTargets: string[];
  if (urgencyLevel >= 8) {
    notificationTargets = ["all_staff", "management", "it_support"];
  } else {
    notificationTargets = ["relevant_staff", "it_support"];
  }

  const dataRecoveryPlan = "sync_paper_to_electronic_after_recovery";
  const estimatedRecoveryTime = calculateRecoveryTime(failureType);

  return {
    alternativeProcess,
    notificationTargets,
    dataRecoveryPlan,
    estimatedRecoveryTime
  };
}
