// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-2-2-1
// 関数: validateApplicationInput, validateApplicationAmountAndPeriod, determineApprovalHierarchy, determineApprovalAuthority, determineApprovalDecision, determineNextApprover, setApproverAuthorityLevel

export interface ValidationResult { isValid: boolean; errors: string[]; warnings: string[] }

export interface AmountPeriodValidationResult { isAmountValid: boolean; isPeriodValid: boolean; validationErrors: string[]; canProceed: boolean }

export interface ApprovalHierarchyResult { approvalLevel: string; approvers: string[]; estimatedDays: number; requiresPaperApproval: boolean }

export interface ApprovalAuthorityResult { hasAuthority: boolean; requiredPosition: string; nextApprover: string | null; processingRoute: string }

export interface ApprovalDecisionResult { decision: string; reason: string; conditionalRequirements: string[]; nextAction: string }

export interface NextApproverResult { nextApprover: string | null; processingRoute: string; isSubsidyRelated: boolean; requiresPaperStorage: boolean }

export interface ApproverAuthorityLevelResult { requiredAuthorityLevel: string; approverRoles: string[]; escalationRequired: boolean }

export interface BudgetLimits { [key: string]: { minAmount: number; maxAmount: number } }

interface ValidateApplicationInputApplicationType {
  [key: string]: boolean;
}

interface ValidateApplicationInputDepartment {
  [key: string]: boolean;
}

interface ValidateApplicationInputUrgencyLevel {
  [key: string]: boolean;
}

const validateApplicationInputValidApplicationTypes: ValidateApplicationInputApplicationType = {
  '補助金申請': true,
  '設備申請': true,
  '人事申請': true,
  '予算申請': true,
  '研究申請': true
};

const validateApplicationInputValidDepartments: ValidateApplicationInputDepartment = {
  '研究推進部': true,
  '総務部': true,
  '経理部': true,
  '人事部': true,
  '企画部': true,
  '技術部': true,
  '営業部': true
};

const validateApplicationInputValidUrgencyLevels: ValidateApplicationInputUrgencyLevel = {
  '通常': true,
  '急ぎ': true,
  '至急': true,
  '高': true,
  '中': true,
  '低': true
};

function validateApplicationInputIsValidApplicationType(applicationType: string): boolean {
  return validateApplicationInputValidApplicationTypes[applicationType] === true;
}

function validateApplicationInputIsValidDepartment(department: string): boolean {
  return validateApplicationInputValidDepartments[department] === true;
}

function validateApplicationInputIsValidUrgencyLevel(urgencyLevel: string): boolean {
  return validateApplicationInputValidUrgencyLevels[urgencyLevel] === true;
}

export function validateApplicationInput(
  documentTitle: string,
  documentContent: string,
  applicationType: string,
  applicantDepartment: string,
  urgencyLevel: string
): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  
  if (!documentTitle || documentTitle.length < 10 || documentTitle.length > 200) {
    errors.push("申請書類のタイトルは10文字以上200文字以内で入力してください");
  }
  
  if (!documentContent || documentContent.length < 50) {
    errors.push("申請内容は50文字以上で詳しく記載してください");
  }
  
  if (!applicationType || !validateApplicationInputIsValidApplicationType(applicationType)) {
    errors.push("申請種別を正しく選択してください");
  }
  
  if (!applicantDepartment || !validateApplicationInputIsValidDepartment(applicantDepartment)) {
    errors.push("所属部署を正しく入力してください");
  }
  
  if (!urgencyLevel || !validateApplicationInputIsValidUrgencyLevel(urgencyLevel)) {
    errors.push("緊急度を選択してください");
  }
  
  const isValid = errors.length === 0;
  
  return { isValid, errors, warnings };
}

export function validateApplicationAmountAndPeriod(
  applicationAmount: number,
  implementationStartDate: string,
  implementationEndDate: string,
  documentType: string,
  budgetLimits: BudgetLimits
): AmountPeriodValidationResult {
  const budgetLimit = budgetLimits[documentType];
  
  // 申請金額が予算上限の150%を超過している場合はエラーを投げる
  if (applicationAmount > budgetLimit.maxAmount * 1.5) {
    throw new Error("申請金額が大幅に予算上限を超過しています。金額を見直してください");
  }
  
  const isAmountValid = applicationAmount >= budgetLimit.minAmount && applicationAmount <= budgetLimit.maxAmount;
  
  const startDate = new Date(implementationStartDate);
  const endDate = new Date(implementationEndDate);
  const today = new Date();
  const isPeriodValid = startDate >= today && endDate > startDate;
  
  const validationErrors: string[] = [];
  if (!isAmountValid) {
    validationErrors.push("申請金額が規定範囲外です");
  }
  if (!isPeriodValid) {
    validationErrors.push("実施期間が不正です");
  }
  
  const canProceed = isAmountValid && isPeriodValid;
  
  return {
    isAmountValid,
    isPeriodValid,
    validationErrors,
    canProceed
  };
}

export function determineApprovalHierarchy(applicationAmount: number, documentType: string, applicantDepartment: string): ApprovalHierarchyResult {
  // バリデーション
  if (applicationAmount <= 0) {
    throw new Error("申請金額は1円以上で入力してください");
  }
  
  if (!applicantDepartment || applicantDepartment.trim() === "") {
    throw new Error("承認ルート設定のため、所属部署を入力してください");
  }

  let approvalLevel = "";
  let estimatedDays = 0;
  let requiresPaperApproval = false;
  
  // 補助金関連の判定
  if (documentType.includes("補助金")) {
    if (applicationAmount >= 1000000) {
      approvalLevel = "理事承認";
      estimatedDays = 7;
    } else {
      approvalLevel = "部長承認";
      estimatedDays = 5;
    }
    requiresPaperApproval = true;
  } else {
    // 一般申請の場合
    if (applicationAmount < 100000) {
      approvalLevel = "課長承認";
      estimatedDays = 3;
    } else if (applicationAmount < 1000000) {
      approvalLevel = "部長承認";
      estimatedDays = 5;
    } else {
      approvalLevel = "理事承認";
      estimatedDays = 7;
    }
    requiresPaperApproval = false;
  }
  
  // 承認者リストの決定
  let approvers: string[] = [];
  if (approvalLevel === "課長承認") {
    approvers = ["課長"];
  } else if (approvalLevel === "部長承認") {
    approvers = ["部長"];
  } else if (approvalLevel === "理事承認") {
    approvers = ["理事"];
  }

  return {
    approvalLevel,
    approvers,
    estimatedDays,
    requiresPaperApproval
  };
}

export function determineApprovalAuthority(
  approverPosition: string,
  applicationAmount: number,
  applicationType: string,
  approvalAction: string
): ApprovalAuthorityResult {
  // バリデーション
  if (!approverPosition || approverPosition.trim() === "") {
    throw new Error("承認者の職位情報を確認できません。システム管理者にお問い合わせください。");
  }
  
  if (applicationAmount < 0) {
    throw new Error("申請金額に正しい値を入力してください。");
  }
  
  if (!applicationType || applicationType.trim() === "") {
    throw new Error("申請種別を選択してください。");
  }

  // 職位レベルの定義
  const positionLevels: { [key: string]: number } = {
    "主任": 1,
    "係長": 2,
    "課長": 3,
    "部長": 4,
    "理事": 5,
    "役員": 6
  };

  // 申請種別と金額から必要な職位を判定
  function determineRequiredPositionInternal(type: string, amount: number): string {
    if (type === "補助金申請") {
      if (amount >= 5000000) {
        return "理事";
      } else if (amount >= 1000000) {
        return "部長";
      } else {
        return "課長";
      }
    } else {
      if (amount >= 10000000) {
        return "理事";
      } else if (amount >= 3000000) {
        return "部長";
      } else {
        return "課長";
      }
    }
  }

  // 権限レベルチェック
  function checkAuthorityLevelInternal(currentPosition: string, requiredPosition: string): boolean {
    const currentLevel = positionLevels[currentPosition] || 0;
    const requiredLevel = positionLevels[requiredPosition] || 0;
    return currentLevel >= requiredLevel;
  }

  // 次の承認者を特定
  function findNextApproverInternal(requiredPosition: string): string {
    return requiredPosition;
  }

  const requiredPosition = determineRequiredPositionInternal(applicationType, applicationAmount);
  const hasAuthority = checkAuthorityLevelInternal(approverPosition, requiredPosition);

  if (!hasAuthority) {
    const nextApprover = findNextApproverInternal(requiredPosition);
    return {
      hasAuthority: false,
      requiredPosition,
      nextApprover,
      processingRoute: "escalate"
    };
  }

  let processingRoute: string;
  if (approvalAction === "approve") {
    processingRoute = "approved";
  } else if (approvalAction === "reject") {
    processingRoute = "rejected";
  } else {
    processingRoute = "returned";
  }

  return {
    hasAuthority: true,
    requiredPosition,
    nextApprover: null,
    processingRoute
  };
}

export function determineApprovalDecision(
  documentContent: string,
  deficiencyItems: string[],
  subsidyRelated: boolean,
  urgencyLevel: number
): ApprovalDecisionResult {
  // 制約チェック
  if (!documentContent || documentContent.trim() === "") {
    throw new Error("申請書類の内容が入力されていません。承認判定を行うことができません。");
  }

  // 緊急度レベルのクランプ
  const clampedUrgencyLevel = Math.max(1, Math.min(5, urgencyLevel));

  // 不備の重要度スコアを計算
  const calculateDeficiencySeverity = (items: string[]): number => {
    let score = 0;
    for (const item of items) {
      if (item.includes("金額") || item.includes("期間") || item.includes("添付")) {
        score += 3;
      } else {
        score += 1;
      }
    }
    return score;
  };

  // 条件付承認の要件を生成
  const generateConditionalRequirements = (items: string[]): string[] => {
    return items.map(item => `${item}を修正してください`);
  };

  const severityScore = calculateDeficiencySeverity(deficiencyItems);
  const deficiencyCount = deficiencyItems.length;

  // 補助金関連で重要な不備がある場合
  if (subsidyRelated && severityScore >= 7) {
    return {
      decision: "reject",
      reason: "補助金関連書類で重要な不備があるため",
      conditionalRequirements: [],
      nextAction: "resubmit"
    };
  }

  // 重大な不備が複数ある場合
  if (deficiencyCount >= 3 || severityScore >= 8) {
    return {
      decision: "reject",
      reason: "重大な不備が複数あるため",
      conditionalRequirements: [],
      nextAction: "resubmit"
    };
  }

  // 軽微な不備があるが緊急性を考慮
  if (deficiencyCount >= 1 && clampedUrgencyLevel >= 4) {
    const requirements = generateConditionalRequirements(deficiencyItems);
    return {
      decision: "conditional",
      reason: "軽微な不備があるが緊急性を考慮",
      conditionalRequirements: requirements,
      nextAction: "fulfill_conditions"
    };
  }

  // 不備なしまたは軽微な不備のみ
  return {
    decision: "approve",
    reason: "不備なしまたは軽微な不備のみ",
    conditionalRequirements: [],
    nextAction: "proceed"
  };
}

export function determineNextApprover(
  documentTitle: string,
  documentContent: string,
  currentApproverRole: string,
  approvalDecision: string
): NextApproverResult {
  // バリデーション
  if (!documentTitle || documentTitle.trim() === "") {
    throw new Error("申請書類のタイトルが入力されていません。タイトルを入力してください。");
  }
  
  if (!currentApproverRole || currentApproverRole.trim() === "") {
    throw new Error("承認者の役職情報が取得できません。システ管理者にお問い合わせください。");
  }
  
  if (!approvalDecision || approvalDecision.trim() === "") {
    throw new Error("承認・差戻し・却下のいずれかを選択してください。");
  }

  // 補助金関連キーワードの分析
  const subsidyKeywords = [
    "科研費", "科学研究費", "補助金", "運営費交付金", "文部科学省", 
    "設備整備費", "研究費", "助成事業", "研究設備", "交付金"
  ];
  
  const titleContent = documentTitle + " " + documentContent;
  let keywordCount = 0;
  let totalWords = titleContent.split(/\s+/).length;
  
  subsidyKeywords.forEach(keyword => {
    if (titleContent.includes(keyword)) {
      keywordCount += keyword.length;
    }
  });
  
  const keywordScore = keywordCount / Math.max(totalWords, 1);
  const isSubsidyRelated = keywordScore >= 0.7 || 
    subsidyKeywords.some(keyword => titleContent.includes(keyword));
  
  // 文部科学省要件チェック
  const moeKeywords = ["文部科学省", "科研費", "科学研究費", "運営費交付金", "設備整備費"];
  const requiresPaperStorage = isSubsidyRelated && 
    moeKeywords.some(keyword => documentTitle.includes(keyword));
  
  // 処理ルート決定
  const processingRoute = requiresPaperStorage ? "hybrid" : "electronic";
  
  // 次の承認者決定
  let nextApprover: string | null = null;
  
  // 差し戻しまたは却下の場合は次の承認者なし
  if (approvalDecision === "差し戻し" || approvalDecision === "差戻し" || 
      approvalDecision === "reject" || approvalDecision === "却下") {
    nextApprover = null;
  } else if (approvalDecision === "承認" || approvalDecision === "approve") {
    // 承認の場合の次の承認者決定
    if (currentApproverRole === "課長" || currentApproverRole === "section_chief") {
      nextApprover = currentApproverRole === "section_chief" ? "department_head" : "部長";
    } else if (currentApproverRole === "部長" || currentApproverRole === "department_head") {
      if (isSubsidyRelated) {
        nextApprover = "理事";
      } else {
        nextApprover = null; // 部長で完結
      }
    } else if (currentApproverRole === "理事") {
      nextApprover = null; // 理事で最終
    }
  }
  
  return {
    nextApprover,
    processingRoute,
    isSubsidyRelated,
    requiresPaperStorage
  };
}

export function setApproverAuthorityLevel(
  documentType: string,
  subsidyRelated: boolean,
  paperStorageRequired: boolean,
  applicantDepartment: string,
  budgetAmount: number
): ApproverAuthorityLevelResult {
  if (applicantDepartment === "") {
    throw new Error("申請者の所属部署を選択してください");
  }
  
  if (budgetAmount < 0) {
    throw new Error("予算金額は0以上の値を入力してください");
  }

  const isHighBudget = budgetAmount > 5000000;
  const isVeryHighBudget = budgetAmount > 10000000;
  const needsHighAuthority = subsidyRelated || isHighBudget;
  const requiredAuthorityLevel = needsHighAuthority ? "department_head" : "section_chief";
  const approverRoles = [requiredAuthorityLevel];
  
  if (paperStorageRequired) {
    approverRoles.push("administrative_director");
  }
  
  const escalationRequired = isVeryHighBudget;
  
  return { requiredAuthorityLevel, approverRoles, escalationRequired };
}
