// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1
// 関数: handleSystemFailureAlternativeProcess, checkApprovalStatusViewPermission, handleSystemFailureFallback, ensureBusinessContinuityDuringSystemUpdate

export interface SystemFailureResult { alternativeProcess: string; notificationTargets: string[]; dataRecoveryPlan: string; estimatedRecoveryTime: number }

export interface ViewPermissionResult { canView: boolean; viewLevel: string; allowedFields: string[] }

export interface SystemFallbackResult { fallbackMethod: string; emergencyContactList: string[]; paperFormUrl: string; syncRequired: boolean }

export interface BusinessContinuityResult { continuityPlan: string; temporaryRoutes: string[]; rollbackProcedure: string; communicationPlan: string }

export function handleSystemFailureAlternativeProcess(
  systemStatus: string,
  failureType: string,
  documentType: string,
  urgencyLevel: number
): SystemFailureResult {
  // システム状況の検証
  if (!systemStatus || systemStatus === "unknown" || systemStatus === "") {
    throw new Error("システム状況を確認できません。情報システム課に連絡してください。");
  }

  // 緊急度レベルの検証
  if (urgencyLevel < 1 || urgencyLevel > 10) {
    throw new Error("緊急度は1から10の範囲で指定してください。");
  }

  // 障害の種類が指定されていない場合の警告
  if (!failureType) {
    console.warn("障害の詳細が不明です。標準的な代替処理を開始します。");
  }

  let alternativeProcess: string;
  let notificationTargets: string[];
  const dataRecoveryPlan = "sync_paper_to_electronic_after_recovery";

  // システム状況に基づく代替処理の決定
  if (systemStatus === "critical_failure") {
    alternativeProcess = "full_paper_mode";
  } else if (systemStatus === "partial_failure") {
    alternativeProcess = "manual_hybrid_mode";
  } else {
    alternativeProcess = "temporary_workaround";
  }

  // 緊急度に基づく通知対象の決定
  if (urgencyLevel >= 8) {
    notificationTargets = ["all_staff", "management", "it_support"];
  } else {
    notificationTargets = ["relevant_staff", "it_support"];
  }

  // 復旧時間の計算
  function calculateRecoveryTime(failureType: string): number {
    const recoveryTimeMap: { [key: string]: number } = {
      "database_connection": 240,
      "network_failure": 240,
      "system_sync_error": 240,
      "system_down": 240,
      "api_timeout": 120,
      "database_timeout": 120,
      "network_delay": 60,
      "slow_response": 60
    };

    // 障害タイプに基づく復旧時間、または代替処理タイプに基づくデフォルト時間
    if (recoveryTimeMap[failureType]) {
      return recoveryTimeMap[failureType];
    }

    // 代替処理タイプに基づくデフォルト復旧時間
    switch (alternativeProcess) {
      case "full_paper_mode":
        return 240;
      case "manual_hybrid_mode":
        return 120;
      case "temporary_workaround":
        return 60;
      default:
        return 120;
    }
  }

  const estimatedRecoveryTime = calculateRecoveryTime(failureType);

  return {
    alternativeProcess,
    notificationTargets,
    dataRecoveryPlan,
    estimatedRecoveryTime
  };
}

function getUserDepartment(userId: string): string {
  return userId.includes('admin') || userId.includes('mgr') ? 'dept_general_affairs' : 
         userId.includes('user001') || userId.includes('user003') ? 'dept001' :
         userId.includes('user005') || userId.includes('user006') ? 'dept003' :
         userId.includes('user007') ? 'dept004' :
         userId.includes('user004') || userId.includes('user005') || userId.includes('user006') ? 'dept_research' :
         userId.includes('user007') || userId.includes('user008') ? 'dept_other' :
         'dept001';
}

function getApplicationDepartment(applicationId: string): string {
  return applicationId.includes('app_20240315') ? 'dept_general_affairs' : 'dept001';
}

export function checkApprovalStatusViewPermission(
  userId: string,
  applicationId: string,
  userRole: string,
  applicationOwner: string,
  departmentId: string
): ViewPermissionResult {
  if (!userId || userId.trim() === '') {
    throw new Error("利用者の認証情報が確認できません。再度ログインしてください。");
  }
  
  if (!applicationId || applicationId.trim() === '') {
    throw new Error("指定された申請書類が見つかりません。");
  }

  const isOwner = userId === applicationOwner;
  if (isOwner) {
    return { canView: true, viewLevel: "full", allowedFields: ["status", "currentApprover", "history", "comments"] };
  }

  const isManager = userRole === "manager" || userRole === "director";
  const sameDepartment = getUserDepartment(userId) === getApplicationDepartment(applicationId);
  
  if (isManager && sameDepartment) {
    return { canView: true, viewLevel: "progress", allowedFields: ["status", "currentApprover"] };
  }
  
  if (sameDepartment) {
    return { canView: true, viewLevel: "basic", allowedFields: ["status"] };
  }
  
  return { canView: false, viewLevel: "none", allowedFields: [] };
}

function getApplicationInfo(applicationId: string) {
  if (!applicationId || applicationId.trim() === '') {
    throw new Error("指定された申請書類が見つかりません。正しい申請番号を入力してください。");
  }
  
  // 長時間障害のケースを判定
  if (applicationId === "APP-LONG-DOWN") {
    console.warn("システム障害が長時間継続しています。緊急の場合は情報システム課まで直接お電話ください。");
  }
  
  // 申請書類の種類と優先度を判定
  const isSubsidy = applicationId.includes("subsidy") || applicationId === "APP-002" || applicationId === "APP-003";
  const isHighPriority = applicationId.includes("urgent") || applicationId === "APP-002" || applicationId === "APP-003";
  
  return {
    type: isSubsidy ? "subsidy" : "general",
    priority: isHighPriority ? "high" : "normal",
    approvers: ["approver1", "approver2"]
  };
}

function getEmergencyContacts(approvers: string[]): string[] {
  return approvers.map(approver => `contact_${approver}`);
}

function generatePaperFormUrl(applicationId: string): string {
  return `http://forms/${applicationId}`;
}

export function handleSystemFailureFallback(
  systemStatus: string,
  applicationId: string,
  userRole: string
): SystemFallbackResult {
  const isSystemDown = systemStatus === "down" || systemStatus === "error";
  
  if (!isSystemDown) {
    return {
      fallbackMethod: "normal",
      emergencyContactList: [],
      paperFormUrl: "",
      syncRequired: false
    };
  }
  
  const applicationInfo = getApplicationInfo(applicationId);
  const isUrgent = applicationInfo.type === "subsidy" || applicationInfo.priority === "high";
  const fallbackMethod = isUrgent ? "emergency_paper" : "wait_recovery";
  const contactList = getEmergencyContacts(applicationInfo.approvers);
  const paperUrl = generatePaperFormUrl(applicationId);
  
  return {
    fallbackMethod,
    emergencyContactList: contactList,
    paperFormUrl: paperUrl,
    syncRequired: true
  };
}

export function ensureBusinessContinuityDuringSystemUpdate(
  updateScope: string,
  activeApplications: number,
  estimatedUpdateDuration: number,
  criticalDeadlines: string[]
): BusinessContinuityResult {
  // エラーチェック
  if (activeApplications === null || activeApplications === undefined) {
    throw new Error("現在の申請状況を確認できないため、安全な更新計画を立てることができません。システム管理者にお問い合わせください。");
  }
  
  if (estimatedUpdateDuration === null || estimatedUpdateDuration === undefined) {
    throw new Error("更新作業の所要時間を入力してください。業務継続計画の策定に必要です。");
  }

  // 警告チェック（影響範囲情報不完全）
  if (updateScope === "") {
    console.warn("影響範囲の詳細が不明な項目があります。より安全な更新計画のため、詳細調査をお勧めします。");
  }

  const impactLevel = activeApplications > 50 || criticalDeadlines.length > 0 ? "high" : "low";
  const requiresStaging = estimatedUpdateDuration > 120;
  const temporaryRoutes = [];
  
  if (updateScope.includes("documentClassification")) {
    temporaryRoutes.push("manual_paper_route");
  }
  
  if (impactLevel === "high") {
    temporaryRoutes.push("emergency_manual_route");
  }
  
  const continuityPlan = requiresStaging ? "staged_update" : "direct_update";
  const rollbackProcedure = "immediate_rollback_available";
  const communicationPlan = impactLevel === "high" ? "advance_notification_required" : "standard_notification";
  
  return { continuityPlan, temporaryRoutes, rollbackProcedure, communicationPlan };
}
