// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-1779263788059-2-1-1
// 関数: validateApplicationBeforeSubmission, analyzeRegulationImpactScope, classifyLegalChangeImpactLevel, migrateExistingDataToNewClassification

export interface ValidationResult { isValid: boolean; errors: string[]; warnings: string[] }

export interface RegulationImpactResult { affectedDocumentTypes: string[]; processingRouteChanges: Array<{documentType: string; oldRoute: string; newRoute: string}>; impactLevel: string; changeRequiredCount: number }

export interface LegalChangeImpactResult { impactLevel: string; priority: number; requiredResponseDays: number; affectedRuleCount: number; riskAssessment: string }

export interface MigrationResult { migratedCount: number; skippedCount: number; errorCount: number; updatedRoutes: Array<{documentId: string; oldRoute: string; newRoute: string}> }

export function validateApplicationBeforeSubmission(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  processingRoute: string,
  approvalRoute: string[],
  requiredFields: Record<string, any>
): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!documentTitle || documentTitle.trim().length === 0) {
    throw new Error("申請書類のタイトルを入力してください");
  }

  if (!documentContent || documentContent.trim().length < 10) {
    throw new Error("申請内容を10文字以上で入力してください");
  }

  if (documentType === "subsidy" && processingRoute === "electronic") {
    throw new Error("補助金関連書類は紙保管が必要なため、ハイブリッド処理を選択してください");
  }

  if (approvalRoute.length === 0) {
    throw new Error("承認者を1名以上設定してください");
  }

  for (const field in requiredFields) {
    if (!requiredFields[field] || (typeof requiredFields[field] === 'string' && requiredFields[field].trim() === '')) {
      errors.push(`必須項目「${field}」を入力してください`);
    }
  }

  if (documentType === "subsidy" && processingRoute !== "hybrid") {
    errors.push("補助金関連書類はハイブリッド処理が必要です");
  }

  const isValid = errors.length === 0;

  return { isValid, errors, warnings };
}

export function analyzeRegulationImpactScope(
  regulationChangeContent: string,
  affectedRegulationTypes: string[],
  currentDocumentTypes: Array<{typeName: string; regulationCategory: string; storageRequirement: string}>
): RegulationImpactResult {
  if (!regulationChangeContent || regulationChangeContent.trim() === "") {
    throw new Error("法令改正の変更内容が正しく取得できていません。改正通知の受信処理を確認してください。");
  }

  if (!currentDocumentTypes || currentDocumentTypes === null) {
    throw new Error("システムに登録されている文書種別の情報を取得できません。データベース接続を確認してください。");
  }

  const affectedRegulations = extractAffectedRegulationsInternal(regulationChangeContent, affectedRegulationTypes);
  const affectedTypes = [];
  const routeChanges = [];

  for (const docType of currentDocumentTypes) {
    if (isRegulationMatchInternal(docType.regulationCategory, affectedRegulations)) {
      affectedTypes.push(docType.typeName);
      const currentRoute = docType.storageRequirement;
      const newRoute = determineNewProcessingRouteInternal(docType, regulationChangeContent);
      if (currentRoute !== newRoute) {
        routeChanges.push({ 
          documentType: docType.typeName, 
          oldRoute: currentRoute, 
          newRoute: newRoute 
        });
      }
    }
  }

  const impactLevel = routeChanges.length === 0 ? "軽微" : routeChanges.length <= 5 ? "中程度" : "重大";

  return {
    affectedDocumentTypes: affectedTypes,
    processingRouteChanges: routeChanges,
    impactLevel: impactLevel,
    changeRequiredCount: routeChanges.length
  };
}

function extractAffectedRegulationsInternal(content: string, types: string[]): string[] {
  const result = [];
  for (const type of types) {
    if (content.includes(type) || content.includes("文部科学省") && type.includes("文部科学省")) {
      result.push(type);
    }
  }
  return result.length > 0 ? result : types;
}

function isRegulationMatchInternal(category: string, affectedRegulations: string[]): boolean {
  return affectedRegulations.some(regulation => 
    category.includes(regulation) || 
    regulation.includes(category) ||
    (category.includes("文部科学省") && regulation.includes("文部科学省"))
  );
}

function determineNewProcessingRouteInternal(docType: {typeName: string; regulationCategory: string; storageRequirement: string}, content: string): string {
  if (content.includes("紙保管を必須") || content.includes("紙保存要件")) {
    return "hybrid";
  }
  if (content.includes("電子保存要件") || content.includes("電子化対応")) {
    return "electronic";
  }
  if (docType.storageRequirement === "electronic") {
    return "hybrid";
  }
  return docType.storageRequirement;
}

export function classifyLegalChangeImpactLevel(
  changeNotification: string,
  affectedDocumentTypes: string[],
  currentProcessingRules: object[],
  complianceDeadline: Date
): LegalChangeImpactResult {
  if (!changeNotification || changeNotification.trim() === '') {
    throw new Error("法令改正通知の内容が正しく取得できません。通知内容を確認してください。");
  }

  const hasSubsidyRequirementChange = changeNotification.includes("補助金") || changeNotification.includes("交付要綱");
  const affectedRuleCount = currentProcessingRules.filter(rule => 
    affectedDocumentTypes.includes((rule as any).document_type)
  ).length;
  const daysUntilDeadline = Math.floor((complianceDeadline.getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24));
  
  let impactLevel: string = "low";
  let priority = 3;
  let requiredResponseDays = 60;
  
  if (hasSubsidyRequirementChange && (affectedRuleCount >= 10 || daysUntilDeadline < 30)) {
    impactLevel = "high";
    priority = 1;
    requiredResponseDays = 14;
  } else if (hasSubsidyRequirementChange && (affectedRuleCount >= 5 || daysUntilDeadline < 60)) {
    impactLevel = "medium";
    priority = 2;
    requiredResponseDays = 30;
  }
  
  const riskAssessment = impactLevel === "high" ? "法令違反リスク高" : impactLevel === "medium" ? "業務遅延リスク中" : "影響軽微";
  
  return { impactLevel, priority, requiredResponseDays, affectedRuleCount, riskAssessment };
}

export function migrateExistingDataToNewClassification(
  newClassificationRules: Array<{documentType: string; processingRoute: string; paperStorageRequired?: boolean}>,
  existingDocuments: Array<{id: string; current_processing_route: string; documentType?: string; document_type?: string}>,
  migrationScope: string
): MigrationResult {
  if (newClassificationRules.length === 0) {
    throw new Error("法令改正に基づく新しい分類基準が設定されていません。分類基準を確認してください。");
  }

  const isInMigrationScopeInternal = (doc: any, scope: string): boolean => {
    const docType = doc.documentType || doc.document_type || '';
    
    if (scope === "補助金関連書類") {
      return docType.includes("補助金");
    }
    
    if (scope === "subsidy_related") {
      return docType.includes("補助金");
    }
    
    if (scope === "補助金関連および設備購入関連") {
      return docType.includes("補助金") || docType.includes("設備");
    }
    
    return true;
  };

  const applyNewRulesInternal = (document: any, rules: any[]): any => {
    const docType = document.documentType || document.document_type || '';
    
    for (const rule of rules) {
      if (rule.documentType === docType) {
        return {
          processingRoute: rule.processingRoute,
          paperStorageRequired: rule.paperStorageRequired
        };
      }
    }
    
    return {
      processingRoute: document.current_processing_route,
      paperStorageRequired: false
    };
  };

  const targetDocuments = existingDocuments.filter(doc => isInMigrationScopeInternal(doc, migrationScope));
  
  let migratedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;
  const updatedRoutes: Array<{documentId: string; oldRoute: string; newRoute: string}> = [];

  for (const document of targetDocuments) {
    try {
      const newClassification = applyNewRulesInternal(document, newClassificationRules);
      if (newClassification.processingRoute !== document.current_processing_route) {
        updatedRoutes.push({
          documentId: document.id,
          oldRoute: document.current_processing_route,
          newRoute: newClassification.processingRoute
        });
        migratedCount++;
      } else {
        skippedCount++;
      }
    } catch (error) {
      errorCount++;
    }
  }

  return {
    migratedCount,
    skippedCount,
    errorCount,
    updatedRoutes
  };
}
