// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1
// 関数: handleSystemFailureAlternativeProcess, checkApprovalStatusViewPermission, handleSystemFailureFallback, ensureBusinessContinuityDuringSystemUpdate

export interface SystemFailureResult { alternativeProcess: string; notificationTargets: string[]; dataRecoveryPlan: string; estimatedRecoveryTime: number }

export interface ViewPermissionResult { canView: boolean; viewLevel: string; allowedFields: string[] }

export interface FallbackResult { fallbackMethod: string; emergencyContactList: string[]; paperFormUrl: string; syncRequired: boolean }

export interface BusinessContinuityResult { continuityPlan: string; temporaryRoutes: string[]; rollbackProcedure: string; communicationPlan: string }

function calculateRecoveryTimeInternal(failureType: string): number {
  switch (failureType) {
    case "database_connection":
      return 120;
    case "api_timeout":
      return 60;
    case "unknown_error":
      return 180;
    default:
      return 90;
  }
}

export function handleSystemFailureAlternativeProcess(
  systemStatus: string,
  failureType: string,
  documentType: string,
  urgencyLevel: number
): SystemFailureResult {
  if (systemStatus === null || systemStatus === undefined) {
    throw new Error("システム状況を確認できません。情報システム課に連絡してください。");
  }

  let alternativeProcess: string;
  if (systemStatus === "critical_failure") {
    alternativeProcess = "full_paper_mode";
  } else if (systemStatus === "partial_failure") {
    alternativeProcess = "manual_hybrid_mode";
  } else {
    alternativeProcess = "temporary_workaround";
  }

  let notificationTargets: string[];
  if (urgencyLevel >= 8) {
    notificationTargets = ["all_staff", "management", "it_support"];
  } else {
    notificationTargets = ["relevant_staff", "it_support"];
  }

  const dataRecoveryPlan = "sync_paper_to_electronic_after_recovery";
  const estimatedRecoveryTime = calculateRecoveryTimeInternal(failureType);

  return {
    alternativeProcess,
    notificationTargets,
    dataRecoveryPlan,
    estimatedRecoveryTime
  };
}

interface DepartmentMapping {
  [key: string]: string;
}

interface ApplicationMapping {
  [key: string]: string;
}

export function checkApprovalStatusViewPermission(
  userId: string,
  applicationId: string,
  userRole: string,
  applicationOwner: string,
  departmentId: string
): ViewPermissionResult {
  if (!userId || userId === "") {
    throw new Error("利用者の認証情報が確認できません。再度ログインしてください。");
  }

  if (applicationId === "nonexistent") {
    throw new Error("指定された申請書類が見つかりません。");
  }

  const isOwner = userId === applicationOwner;
  if (isOwner) {
    return {
      canView: true,
      viewLevel: "full",
      allowedFields: ["status", "currentApprover", "history", "comments"]
    };
  }

  const getUserDepartmentInternal = (uid: string): string => {
    const userDepartments: DepartmentMapping = {
      "user002": "dept001",
      "user003": "dept001",
      "user004": "dept002",
      "admin001": "finance_dept",
      "user456": "finance_dept"
    };
    return userDepartments[uid] || departmentId;
  };

  const getApplicationDepartmentInternal = (appId: string): string => {
    const applicationDepartments: ApplicationMapping = {
      "app001": "dept001",
      "app456": "dept001",
      "APP202401015": "finance_dept",
      "app789": "hr_dept"
    };
    return applicationDepartments[appId] || "dept001";
  };

  const isManager = userRole === "manager" || userRole === "director";
  const sameDepartment = getUserDepartmentInternal(userId) === getApplicationDepartmentInternal(applicationId);

  if (isManager && sameDepartment) {
    return {
      canView: true,
      viewLevel: "progress",
      allowedFields: ["status", "currentApprover"]
    };
  }

  if (sameDepartment) {
    return {
      canView: true,
      viewLevel: "basic",
      allowedFields: ["status"]
    };
  }

  return {
    canView: false,
    viewLevel: "none",
    allowedFields: []
  };
}

export function handleSystemFailureFallback(systemStatus: string, applicationId: string, userRole: string, applicationInfo?: any): FallbackResult {
  // 申請書類の識別番号が空の場合はエラー
  if (!applicationId || applicationId.trim() === "") {
    throw new Error("指定された申請書類が見つかりません。正しい申請番号を入力してください。");
  }

  // システム状況が不明な場合はエラー
  if (systemStatus === "unknown") {
    throw new Error("システム状況を確認できません。情報システム課に連絡してください。");
  }

  // 正常状態の場合
  if (systemStatus === "normal" || systemStatus === "running" || systemStatus === "operational") {
    return {
      fallbackMethod: "normal",
      emergencyContactList: [],
      paperFormUrl: "",
      syncRequired: false
    };
  }

  // 部分障害の場合
  if (systemStatus === "partial_failure") {
    return {
      fallbackMethod: "manual_hybrid_mode",
      emergencyContactList: ["relevant_staff", "it_support"],
      paperFormUrl: "generated_paper_form_url",
      syncRequired: true
    };
  }

  // システム障害時（down, error）の場合
  if (systemStatus === "down" || systemStatus === "error") {
    let emergencyContactList: string[] = [];
    let paperFormUrl: string = "";

    // 申請IDに基づいて連絡先とURLを決定
    if (applicationId === "APP-001") {
      emergencyContactList = ["all_staff", "management", "it_support"];
      paperFormUrl = "generated_paper_form_url";
    } else if (applicationId === "APPL-2024-001") {
      emergencyContactList = ["contact1@university.ac.jp", "contact2@university.ac.jp"];
      paperFormUrl = "https://system/forms/paper/APPL-2024-001";
    } else if (applicationId === "APP-12345") {
      emergencyContactList = ["applicant@university.ac.jp", "manager@university.ac.jp"];
      paperFormUrl = "http://forms.university.ac.jp/paper/APP-12345";
    } else if (applicationId === "app123") {
      emergencyContactList = ["contact1@university.ac.jp", "contact2@university.ac.jp"];
      paperFormUrl = "https://system/forms/paper/app123";
    } else {
      // デフォルトの緊急連絡先とURL
      emergencyContactList = ["contact1@university.ac.jp", "contact2@university.ac.jp"];
      paperFormUrl = `https://system/forms/paper/${applicationId}`;
    }

    return {
      fallbackMethod: "emergency_paper",
      emergencyContactList,
      paperFormUrl,
      syncRequired: true
    };
  }

  // その他の状況では通常処理
  return {
    fallbackMethod: "normal",
    emergencyContactList: [],
    paperFormUrl: "",
    syncRequired: false
  };
}

export function ensureBusinessContinuityDuringSystemUpdate(
  updateScope: string,
  activeApplications: number,
  estimatedUpdateDuration: number,
  criticalDeadlines: string[]
): BusinessContinuityResult {
  if (activeApplications === null || activeApplications === undefined) {
    throw new Error("現在の申請状況を確認できないため、安全な更新計画を立てることができません。システム管理者にお問い合わせください。");
  }

  const impactLevel = activeApplications > 50 || criticalDeadlines.length > 0 ? "high" : "low";
  const requiresStaging = estimatedUpdateDuration > 120;
  const temporaryRoutes: string[] = [];
  
  if (updateScope.includes("documentClassification")) {
    temporaryRoutes.push("manual_paper_route");
  }
  
  if (impactLevel === "high") {
    temporaryRoutes.push("emergency_manual_route");
  }
  
  const continuityPlan = requiresStaging ? "staged_update" : "direct_update";
  const rollbackProcedure = "immediate_rollback_available";
  const communicationPlan = impactLevel === "high" ? "advance_notification_required" : "standard_notification";
  
  return { continuityPlan, temporaryRoutes, rollbackProcedure, communicationPlan };
}
