// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-2-1-1
// 関数: validateApplicationInput, validateApplicationAmountAndPeriod, classifyDocumentTypeAndRoute, determineDocumentTypeAndRoute, checkMoeComplianceRequirements, determineDigitalizationEligibility, determineProcessingRoute, handleDocumentClassificationException, determineDocumentStorageMethod, checkComplianceAndDetermineRoute, handleEmergencyComplianceUpdate

export interface DocumentClassificationResult { documentType: string; processingRoute: 'electronic' | 'hybrid'; subsidyRelated: boolean; paperStorageRequired: boolean; }

export interface ComplianceCheckResult { complianceStatus: string; paperStorageRequired: boolean; processingRoute: string; riskLevel: string; }

export interface ValidationResult { isValid: boolean; errors: string[]; warnings: string[]; }

function isValidApplicationType(applicationType: string): boolean {
  const validTypes = ['補助金申請', '設備申請', '人事申請', '予算申請', '研究申請'];
  return validTypes.includes(applicationType);
}

function isValidDepartment(department: string): boolean {
  const validDepartments = ['理学部事務課', '工学部事務課', '総務課', '経理課', '人事課'];
  return validDepartments.includes(department);
}

function isValidUrgencyLevel(urgencyLevel: string): boolean {
  const validLevels = ['通常', '急ぎ', '至急'];
  return validLevels.includes(urgencyLevel);
}

export function validateApplicationInput(
  documentTitle: string,
  documentContent: string,
  applicationType: string,
  applicantDepartment: string,
  urgencyLevel: string
): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // タイトルのチェック
  if (!documentTitle) {
    throw new Error("申請書類のタイトルは必須項目です。入力してください。");
  }
  if (documentTitle.length < 10 || documentTitle.length > 200) {
    throw new Error("申請書類のタイトルは10文字以上200文字以内で入力してください");
  }

  // 内容のチェック
  if (!documentContent) {
    throw new Error("申請内容は50文字以上で詳しく記載してください。");
  }
  if (documentContent.length < 50) {
    throw new Error("申請内容は50文字以上で詳しく記載してください。");
  }

  // 申請種別のチェック
  if (!applicationType) {
    throw new Error("申請種別を選択してください。");
  }
  if (!isValidApplicationType(applicationType)) {
    errors.push("申請種別を正しく選択してください");
  }

  // 所属部署のチェック
  if (!applicantDepartment) {
    throw new Error("所属部署を入力してください。");
  }
  if (!isValidDepartment(applicantDepartment)) {
    errors.push("所属部署を正しく入力してください");
  }

  // 緊急度のチェック
  if (!urgencyLevel || !isValidUrgencyLevel(urgencyLevel)) {
    errors.push("緊急度を選択してください");
  }

  const isValid = errors.length === 0;

  return { isValid, errors, warnings };
}

export function validateApplicationAmountAndPeriod(
  applicationAmount: number,
  implementationStartDate: string,
  implementationEndDate: string,
  documentType: string,
  budgetLimits: object
): { isAmountValid: boolean; isPeriodValid: boolean; validationErrors: string[]; canProceed: boolean } {
  // 申請金額の基本チェック
  if (applicationAmount <= 0 || !Number.isFinite(applicationAmount)) {
    throw new Error("申請金額は正の数値で入力してください");
  }

  // 日付形式の基本チェック
  const startDate = new Date(implementationStartDate);
  const endDate = new Date(implementationEndDate);
  
  if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
    throw new Error("実施期間は有効な日付形式で入力してください");
  }

  // 予算上限の取得
  const budgetLimit = (budgetLimits as any)[documentType];
  
  // 金額妥当性チェック
  const isAmountValid = budgetLimit && 
    applicationAmount >= budgetLimit.minAmount && 
    applicationAmount <= budgetLimit.maxAmount;

  // 期間妥当性チェック
  const today = new Date();
  today.setHours(0, 0, 0, 0); // 時刻を00:00:00にリセット
  const isPeriodValid = startDate >= today && endDate > startDate;

  // エラーメッセージの生成
  const validationErrors: string[] = [];
  
  if (!isAmountValid) {
    validationErrors.push("申請金額が規定範囲外です");
  }
  
  if (!isPeriodValid) {
    validationErrors.push("実施期間が不正です");
  }

  // 予算上限の150%超過チェック（警告）
  if (budgetLimit && applicationAmount > budgetLimit.maxAmount * 1.5) {
    console.warn("申請金額が大幅に予算上限を超過しています。金額を見直してください");
  }

  const canProceed = isAmountValid && isPeriodValid;

  return {
    isAmountValid,
    isPeriodValid,
    validationErrors,
    canProceed
  };
}

function calculateSubsidyKeywordMatch(title: string, content: string): number {
  const subsidyKeywords = [
    '科研費', '科学研究費', '補助金', '運営費交付金', '設備整備費',
    '文部科学省', '研究費', '助成金', '交付金', '研究補助'
  ];
  
  const text = (title + ' ' + content).toLowerCase();
  const totalWords = text.split(/\s+/).length;
  let matchCount = 0;
  
  subsidyKeywords.forEach(keyword => {
    const regex = new RegExp(keyword, 'gi');
    const matches = text.match(regex);
    if (matches) {
      matchCount += matches.length;
    }
  });
  
  return totalWords > 0 ? matchCount / totalWords : 0;
}

function determineDocumentTypeInternal(title: string, department: string): string {
  const subsidyKeywords = ['科研費', '科学研究費', '補助金', '運営費交付金', '設備整備費'];
  const hasSubsidyKeyword = subsidyKeywords.some(keyword => title.includes(keyword));
  
  if (hasSubsidyKeyword) {
    return '補助金申請書';
  }
  
  return '一般申請書';
}

function isMoeRequiredPaperStorage(documentType: string): boolean {
  return documentType === '補助金申請書';
}

export function classifyDocumentTypeAndRoute(
  documentTitle: string,
  documentContent: string,
  applicantDepartment: string
): DocumentClassificationResult {
  // バリデーション
  if (!documentTitle || documentTitle.length < 10) {
    throw new Error("申請書類のタイトルは10文字以上で入力してください");
  }
  
  if (!documentContent || documentContent.length < 50) {
    throw new Error("申請書類の内容は50文字以上で入力してください");
  }
  
  if (!applicantDepartment) {
    throw new Error("所属部署を選択してください");
  }
  
  // 業務ロジック実行
  const keywordScore = calculateSubsidyKeywordMatch(documentTitle, documentContent);
  const subsidyRelated = keywordScore >= 0.7;
  const documentType = determineDocumentTypeInternal(documentTitle, applicantDepartment);
  const paperStorageRequired = subsidyRelated && isMoeRequiredPaperStorage(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  
  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired
  };
}

function calculateSubsidyKeywordScore(title: string, content: string): number {
  const subsidyKeywords = [
    '科研費', '科学研究費', '運営費交付金', '補助金', '助成金', '文部科学省',
    '研究費', '設備整備費', '研究設備', '基盤研究', '挑戦的研究',
    'JSPS', 'JST', '学術振興会', '科学技術振興機構'
  ];
  
  const text = (title + ' ' + content).toLowerCase();
  const totalWords = text.length;
  let matchedChars = 0;
  
  subsidyKeywords.forEach(keyword => {
    const regex = new RegExp(keyword, 'gi');
    const matches = text.match(regex);
    if (matches) {
      matchedChars += matches.length * keyword.length;
    }
  });
  
  return totalWords > 0 ? Math.min(matchedChars / totalWords, 1.0) : 0;
}

function isResearchDepartment(department: string): boolean {
  const researchDeptKeywords = ['研究', '理学', '工学', '医学', '薬学', '農学', '文学', '法学', '経済学', '教育学'];
  return researchDeptKeywords.some(keyword => department.includes(keyword));
}

function classifyDocumentTypeInternal(title: string, content: string, isSubsidyRelated: boolean): string {
  if (isSubsidyRelated) {
    if (title.includes('科研費') || title.includes('科学研究費') || content.includes('科学研究費')) {
      return '補助金申請';
    }
    if (title.includes('研究') || content.includes('研究')) {
      return '研究関連';
    }
    return '補助金申請';
  }
  return '一般申請';
}

function requiresPaperStorageInternal(isSubsidyRelated: boolean, title: string, content: string): boolean {
  if (!isSubsidyRelated) return false;
  
  const moeKeywords = ['文部科学省', '科研費', '科学研究費', '運営費交付金'];
  const text = title + ' ' + content;
  
  return moeKeywords.some(keyword => text.includes(keyword));
}

export function determineDocumentTypeAndRoute(
  documentTitle: string,
  documentContent: string,
  applicantDepartment: string
): { documentType: string; processingRoute: string; isSubsidyRelated: boolean; requiresPaperStorage: boolean } {
  
  // バリデーション
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error('申請書類のタイトルを入力してください');
  }
  
  if (documentTitle.length < 10) {
    throw new Error('申請書類のタイトルは10文字以上で入力してください');
  }
  
  if (!documentContent || documentContent.trim() === '') {
    throw new Error('申請書類の内容は50文字以上で入力してください');
  }
  
  if (documentContent.length < 10) {
    throw new Error('申請内容が短すぎる可能性があります。内容を確認してください');
  }
  
  if (documentContent.length < 50) {
    throw new Error('申請書類の内容は50文字以上で入力してください');
  }
  
  if (!applicantDepartment || applicantDepartment.trim() === '') {
    throw new Error('申請者の所属部署を選択してください');
  }
  
  // 補助金関連度の計算
  const keywordScore = calculateSubsidyKeywordScore(documentTitle, documentContent);
  const isResearchDept = isResearchDepartment(applicantDepartment);
  const threshold = isResearchDept ? 0.6 : 0.7;
  const isSubsidyRelated = keywordScore >= threshold;
  
  // 文書種別の判定
  const documentType = classifyDocumentTypeInternal(documentTitle, documentContent, isSubsidyRelated);
  
  // 紙保管要否の判定
  const requiresPaperStorage = requiresPaperStorageInternal(isSubsidyRelated, documentTitle, documentContent);
  
  // 処理ルートの決定
  const processingRoute = requiresPaperStorage ? 'hybrid' : 'electronic';
  
  return {
    documentType,
    processingRoute,
    isSubsidyRelated,
    requiresPaperStorage
  };
}

function calculateMoeKeywordMatch(title: string, content: string): number {
  const moeKeywords = ['補助金', '助成金', '文部科学省', '科研費', '運営費交付金', '設備整備費', '研究費'];
  const text = (title + ' ' + content).toLowerCase();
  
  let matchCount = 0;
  for (const keyword of moeKeywords) {
    if (text.includes(keyword)) {
      matchCount++;
    }
  }
  
  return matchCount / moeKeywords.length;
}

function checkMoeRequirementMatch(documentType: string, moeRequirements: string[]): boolean {
  const subsidyTypes = ['補助金申請書', '申請書', '研究申請書'];
  return subsidyTypes.includes(documentType) && moeRequirements.some(req => 
    ['補助金', '科研費', '運営費交付金', '設備整備費'].includes(req)
  );
}

export function checkMoeComplianceRequirements(
  documentTitle: string, 
  documentContent: string, 
  documentType: string, 
  moeRequirements: string[]
): ComplianceCheckResult {
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error('申請書類のタイトルが入力されていません。法令要件の判定ができません。');
  }
  
  if (!documentType || documentType.trim() === '') {
    throw new Error('書類種別の分類が完了していません。先に文書種別の確認を行ってください。');
  }
  
  const keywordScore = calculateMoeKeywordMatch(documentTitle, documentContent);
  const isSubsidyRelated = keywordScore >= 0.6;
  const paperStorageRequired = isSubsidyRelated && checkMoeRequirementMatch(documentType, moeRequirements);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  const complianceStatus = paperStorageRequired ? "compliant" : "review_required";
  const riskLevel = keywordScore >= 0.8 ? "high" : keywordScore >= 0.4 ? "medium" : "low";
  
  return { complianceStatus, paperStorageRequired, processingRoute, riskLevel };
}

export function determineDigitalizationEligibility(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  subsidyRelevanceScore: number
): DocumentClassificationResult {
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error('申請書類のタイトルが入力されていません。タイトルを入力してください。');
  }

  if (subsidyRelevanceScore < 0 || subsidyRelevanceScore > 1) {
    throw new Error('補助金関連度の評価に異常があります。システム管理者にお問い合わせください。');
  }

  if (documentType === '未分類') {
    console.warn('文書種別の分類が完了していません。手動で種別を確認してください。');
  }

  const subsidyRelated = subsidyRelevanceScore >= 0.7;
  const moeRequiredTypes = ["補助金申請書", "事業報告書", "会計報告書", "監査資料"];
  const paperStorageRequired = subsidyRelated && moeRequiredTypes.includes(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";

  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired
  };
}

export function determineProcessingRoute(
  documentType: string,
  subsidyRelatedScore: number,
  documentTitle: string,
  documentContent: string
): { documentType: string; processingRoute: string; subsidyRelated: boolean; paperStorageRequired: boolean; approvalFlow: string } {
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error('申請書類のタイトルを入力してください');
  }

  if (subsidyRelatedScore < 0 || subsidyRelatedScore > 1) {
    throw new Error('補助金関連度の評価に異常があります。システム管理者にお問い合わせください');
  }

  if (documentType === '未分類') {
    console.warn('文書種別を再確認してください。不明な場合は事務局にお問い合わせください');
  }

  const subsidyRelated = subsidyRelatedScore >= 0.7;
  const moeRequiredTypes = ["補助金申請書", "研究費申請書", "設備導入申請書"];
  const paperStorageRequired = subsidyRelated && moeRequiredTypes.includes(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  const approvalFlow = paperStorageRequired ? "special" : "standard";

  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired,
    approvalFlow
  };
}

function determineProcessingRouteInternal(documentType: string): string {
  const hybridTypes = ['補助金申請書', '許可申請書', '認可申請書'];
  return hybridTypes.includes(documentType) ? 'hybrid' : 'electronic';
}

function generateExceptionReasonInternal(autoResult: string | null, objection: string | null): string {
  if (objection) {
    return '職員異議による手動判定';
  }
  if (!autoResult) {
    return '自動分類失敗による手動判定';
  }
  return '例外処理による手動判定';
}

function createLearningDataInternal(title: string, content: string, finalType: string, reason: string): object {
  return {
    title,
    content,
    finalType,
    exceptionReason: reason,
    timestamp: new Date().toISOString()
  };
}

export function handleDocumentClassificationException(
  documentTitle: string,
  documentContent: string,
  autoClassificationResult: string | null,
  staffObjection: string | null,
  managerDecision: string
): { finalDocumentType: string; processingRoute: string; exceptionReason: string; learningData: object } {
  if (!managerDecision || managerDecision.trim() === '') {
    throw new Error('例外処理には事務局長による最終判定が必要です');
  }

  if (autoClassificationResult == null || staffObjection != null) {
    const finalDocumentType = managerDecision;
    const processingRoute = determineProcessingRouteInternal(finalDocumentType);
    const exceptionReason = generateExceptionReasonInternal(autoClassificationResult, staffObjection);
    const learningData = createLearningDataInternal(documentTitle, documentContent, finalDocumentType, exceptionReason);

    if (!exceptionReason || exceptionReason.trim() === '') {
      console.warn('今後の改善のため、例外が発生した理由を記録することを推奨します');
    }

    return { finalDocumentType, processingRoute, exceptionReason, learningData };
  }

  // フォールバック（通常は上記条件で処理される）
  const finalDocumentType = managerDecision;
  const processingRoute = determineProcessingRouteInternal(finalDocumentType);
  const exceptionReason = '手動判定による処理';
  const learningData = createLearningDataInternal(documentTitle, documentContent, finalDocumentType, exceptionReason);

  return { finalDocumentType, processingRoute, exceptionReason, learningData };
}

function computeKeywordMatch(title: string, content: string, keywords: string[]): number {
  if (keywords.length === 0) return 0;
  
  const text = (title + ' ' + content).toLowerCase();
  const matchedKeywords = keywords.filter(keyword => 
    text.includes(keyword.toLowerCase())
  );
  
  return matchedKeywords.length / keywords.length;
}

function isMoeRequirement(documentType: string): boolean {
  const moeTypes = ['補助金申請書', '事業報告書'];
  return moeTypes.includes(documentType);
}

export function determineDocumentStorageMethod(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  subsidyKeywords: string[]
): DocumentClassificationResult {
  if (documentTitle === '') {
    throw new Error('申請書類のタイトルが入力されていません。タイトルを入力してください。');
  }
  
  if (documentContent.length < 10) {
    throw new Error('申請内容が短すぎる可能性があります。内容を確認してください。');
  }
  
  const score = computeKeywordMatch(documentTitle, documentContent, subsidyKeywords);
  const subsidyRelated = score >= 0.7;
  const paperStorageRequired = subsidyRelated && isMoeRequirement(documentType);
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  
  return {
    documentType,
    processingRoute,
    subsidyRelated,
    paperStorageRequired
  };
}

function calculateKeywordMatchScore(title: string, content: string, keywords: string[]): number {
  const text = (title + ' ' + content).toLowerCase();
  const matchedKeywords = keywords.filter(keyword => 
    text.includes(keyword.toLowerCase())
  );
  return keywords.length > 0 ? matchedKeywords.length / keywords.length : 0;
}

function isMoeComplianceRequired(documentType: string): boolean {
  const moeRequiredTypes = ['補助金申請書', '科研費申請書', '文部科学省関連書類'];
  return moeRequiredTypes.some(type => documentType.includes(type) || documentType.includes('補助金'));
}

function evaluateComplianceStatus(subsidyRelated: boolean, paperRequired: boolean, documentType: string): string {
  if (subsidyRelated && paperRequired) {
    return 'compliant';
  }
  if (!subsidyRelated) {
    return 'review_required';
  }
  return 'compliant';
}

function determineRiskLevel(subsidyRelated: boolean, paperRequired: boolean): string {
  if (subsidyRelated && paperRequired) {
    return 'high';
  }
  return 'low';
}

export function checkComplianceAndDetermineRoute(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  subsidyKeywords: string[],
  moeRequirements?: any,
  applicantDepartment?: string,
  urgencyLevel?: string
): ComplianceCheckResult {
  // バリデーション
  if (!documentTitle || documentTitle.length < 10) {
    throw new Error("申請書類のタイトルは10文字以上で入力してください");
  }
  
  if (!documentContent || documentContent.length < 50) {
    throw new Error("申請書類の内容は50文字以上で入力してください");
  }
  
  if (!documentType || documentType.trim() === "") {
    throw new Error("書類種別の分類が完了していません。先に文書種別の確認を行ってください。");
  }

  // キーワードマッチング計算
  const keywordScore = calculateKeywordMatchScore(documentTitle, documentContent, subsidyKeywords);
  
  // 補助金関連判定（70%以上で補助金関連）
  const subsidyRelated = keywordScore >= 0.7;
  
  // 文部科学省要件による紙保管必要性判定
  const paperStorageRequired = subsidyRelated && isMoeComplianceRequired(documentType);
  
  // 処理ルート決定
  const processingRoute = paperStorageRequired ? "hybrid" : "electronic";
  
  // 法令要件適合状況評価
  const complianceStatus = evaluateComplianceStatus(subsidyRelated, paperStorageRequired, documentType);
  
  // リスクレベル決定
  const riskLevel = determineRiskLevel(subsidyRelated, paperStorageRequired);

  return {
    complianceStatus,
    paperStorageRequired,
    processingRoute,
    riskLevel
  };
}

function extractComplianceKeywords(regulationNotice: string): string[] {
  const keywords = [];
  if (regulationNotice.includes('文書保管') || regulationNotice.includes('保管')) {
    keywords.push('保管');
  }
  if (regulationNotice.includes('補助金') || regulationNotice.includes('研究費') || regulationNotice.includes('設備')) {
    keywords.push('補助金関連');
  }
  if (regulationNotice.includes('改正')) {
    keywords.push('改正');
  }
  return keywords;
}

function isAffectedByRegulationInternal(docType: string, keywords: string[]): boolean {
  if (keywords.includes('補助金関連')) {
    return docType.includes('補助金') || docType.includes('研究費') || docType.includes('設備');
  }
  if (keywords.includes('保管') && keywords.includes('改正')) {
    return docType.includes('補助金') || docType.includes('研究費') || docType.includes('設備');
  }
  return false;
}

function evaluateNewPaperRequirementInternal(docType: string, regulationNotice: string): boolean {
  if (regulationNotice.includes('詳細な判定条件については追って通知予定')) {
    return true; // 最も安全な方式を選択
  }
  if (regulationNotice.includes('軽微')) {
    return false;
  }
  return docType.includes('補助金') || docType.includes('研究費') || docType.includes('設備');
}

function determineEmergencyLevelInternal(affectedCount: number, regulationNotice: string): string {
  if (affectedCount >= 3) {
    return '高';
  }
  if (regulationNotice.includes('軽微')) {
    return '低';
  }
  if (affectedCount > 0) {
    return '中';
  }
  return '低';
}

function getNotificationTargetsInternal(affectedTypes: string[], emergencyLevel: string): string[] {
  if (emergencyLevel === '高' && affectedTypes.length > 0) {
    return ['広報課', '事務局', '情報システム課'];
  }
  if (emergencyLevel === '中' && affectedTypes.length > 0) {
    return ['事務局', '情報システム課'];
  }
  if (emergencyLevel === '低' || affectedTypes.length === 0) {
    return [];
  }
  return [];
}

export function handleEmergencyComplianceUpdate(
  regulationNotice: string,
  currentDocumentTypes: string[],
  existingProcessingRoutes: object[]
): { affectedDocumentTypes: string[]; updatedRoutes: object[]; notificationTargets: string[]; emergencyLevel: string } {
  if (!regulationNotice || regulationNotice.trim() === '') {
    throw new Error('法令改正通知の内容を正しく読み込めませんでした。通知内容を確認してください。');
  }
  
  if (!currentDocumentTypes || currentDocumentTypes.length === 0) {
    throw new Error('システムエラーにより申請書類の種別情報を取得できませんでした。システム管理者に連絡してください。');
  }

  const keywords = extractComplianceKeywords(regulationNotice);
  const affectedTypes = [];
  
  for (const docType of currentDocumentTypes) {
    if (isAffectedByRegulationInternal(docType, keywords)) {
      affectedTypes.push(docType);
    }
  }

  if (affectedTypes.length > 100) {
    console.warn('大規模な法令改正により多数の申請書類に影響があります。段階的な対応を検討してください。');
  }

  const updatedRoutes = [];
  for (const docType of affectedTypes) {
    const newPaperRequired = evaluateNewPaperRequirementInternal(docType, regulationNotice);
    const newRoute = newPaperRequired ? 'hybrid' : 'electronic';
    updatedRoutes.push({ 
      documentType: docType, 
      processingRoute: newRoute, 
      paperStorageRequired: newPaperRequired 
    });
  }

  const emergencyLevel = determineEmergencyLevelInternal(affectedTypes.length, regulationNotice);
  const notificationTargets = getNotificationTargetsInternal(affectedTypes, emergencyLevel);

  return { 
    affectedDocumentTypes: affectedTypes, 
    updatedRoutes, 
    notificationTargets, 
    emergencyLevel 
  };
}
