// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-1779263788059-2-1-1
// 関数: validateApplicationBeforeSubmission, analyzeRegulationImpactScope, classifyLegalChangeImpactLevel, migrateExistingDataToNewClassification, setApproverAuthorityLevel, determineApprovalHierarchy, setApprovalDeadline

export interface ValidationResult { isValid: boolean; errors: string[]; warnings: string[] }

export interface DocumentType { typeName: string; regulationCategory: string; storageRequirement: string }

export interface ProcessingRouteChange { documentType: string; oldRoute: string; newRoute: string }

export interface RouteUpdate { documentId: string; oldRoute: string; newRoute: string }

export interface ClassificationRule { documentType: string; processingRoute: string; paperStorageRequired: boolean }

export interface Document { id: string; type?: string; documentType?: string; current_processing_route: string; title?: string; content?: string }

export function validateApplicationBeforeSubmission(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  processingRoute: string,
  approvalRoute: string[],
  requiredFields: Record<string, any>
): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!documentTitle || documentTitle.trim().length === 0) {
    throw new Error("申請書類のタイトルを入力してください");
  }

  if (!documentContent || documentContent.trim().length < 10) {
    throw new Error("申請内容を10文字以上で入力してください");
  }

  for (const field in requiredFields) {
    if (!requiredFields[field]) {
      errors.push(`必須項目「${field}」を入力してください`);
    }
  }

  if (documentType === "subsidy" && processingRoute !== "hybrid") {
    throw new Error("補助金関連書類はハイブリッド処理が必要です");
  }

  if (documentType === "subsidy" && processingRoute === "electronic") {
    throw new Error("補助金関連書類は紙保管が必要なため、ハイブリッド処理を選択してください");
  }

  if (approvalRoute.length === 0) {
    throw new Error("承認者を1名以上設定してください");
  }

  const isValid = errors.length === 0;

  return { isValid, errors, warnings };
}

function extractAffectedRegulations(regulationChangeContent: string, affectedRegulationTypes: string[]): string[] {
  if (!regulationChangeContent || regulationChangeContent.trim().length < 10) {
    throw new Error("法令改正の変更内容が正しく取得できていません。改正通知の受信処理を確認してください。");
  }
  
  return affectedRegulationTypes.filter(regType => 
    regulationChangeContent.includes(regType) || 
    regulationChangeContent.includes("補助金") && regType.includes("補助金") ||
    regulationChangeContent.includes("研究") && regType.includes("補助金")
  );
}

function isRegulationMatch(regulationCategory: string, affectedRegulations: string[]): boolean {
  return affectedRegulations.some(reg => 
    regulationCategory.includes(reg) || 
    reg.includes(regulationCategory) ||
    (regulationCategory.includes("補助金") && reg.includes("補助金")) ||
    (regulationCategory === "補助金法" && reg.includes("補助金")) ||
    (regulationCategory === "補助金関連" && reg.includes("補助金")) ||
    (regulationCategory === "補助金関連法令" && reg.includes("補助金"))
  );
}

function determineNewProcessingRouteInternal(docType: DocumentType, regulationChangeContent: string): string {
  if (regulationChangeContent.includes("電子保存要件が変更") || 
      regulationChangeContent.includes("保管要件が変更") ||
      regulationChangeContent.includes("電子化に関する法令改正")) {
    return "hybrid";
  }
  return docType.storageRequirement;
}

export function analyzeRegulationImpactScope(
  regulationChangeContent: string, 
  affectedRegulationTypes: string[], 
  currentDocumentTypes: DocumentType[]
): { affectedDocumentTypes: string[]; processingRouteChanges: ProcessingRouteChange[]; impactLevel: string; changeRequiredCount: number } {
  
  if (!regulationChangeContent || regulationChangeContent.trim().length < 10) {
    throw new Error("法令改正の変更内容が正しく取得できていません。改正通知の受信処理を確認してください。");
  }
  
  if (!currentDocumentTypes || currentDocumentTypes.length === 0) {
    throw new Error("システムに登録されている文書種別の情報を取得できません。データベース接続を確認してください。");
  }

  const affectedRegulations = extractAffectedRegulations(regulationChangeContent, affectedRegulationTypes);
  const affectedTypes: string[] = [];
  const routeChanges: ProcessingRouteChange[] = [];
  
  for (const docType of currentDocumentTypes) {
    if (isRegulationMatch(docType.regulationCategory, affectedRegulations)) {
      affectedTypes.push(docType.typeName);
      const currentRoute = docType.storageRequirement;
      const newRoute = determineNewProcessingRouteInternal(docType, regulationChangeContent);
      if (currentRoute !== newRoute) {
        routeChanges.push({ 
          documentType: docType.typeName, 
          oldRoute: currentRoute, 
          newRoute: newRoute 
        });
      }
    }
  }
  
  if (affectedTypes.length > 100) {
    console.warn("影響範囲が非常に広範囲です。段階的な対応計画の策定を推奨します。");
  }
  
  const impactLevel = routeChanges.length === 0 ? "軽微" : routeChanges.length <= 5 ? "中程度" : "重大";
  
  return { 
    affectedDocumentTypes: affectedTypes, 
    processingRouteChanges: routeChanges, 
    impactLevel: impactLevel, 
    changeRequiredCount: routeChanges.length 
  };
}

export function classifyLegalChangeImpactLevel(
  changeNotification: string,
  affectedDocumentTypes: string[],
  currentProcessingRules: any[],
  complianceDeadline: Date
): { impactLevel: string; priority: number; requiredResponseDays: number; affectedRuleCount: number; riskAssessment: string } {
  if (!changeNotification || changeNotification.trim() === "") {
    throw new Error("法令改正通知の内容が正しく取得できません。通知内容を確認してください。");
  }

  const now = new Date();
  if (complianceDeadline.getTime() < now.getTime()) {
    console.warn("施行日が過去の日付です。緊急対応が必要な可能性があります。");
  }

  const hasSubsidyRequirementChange = changeNotification.includes("補助金") || changeNotification.includes("交付要綱");
  const affectedRuleCount = currentProcessingRules.filter(rule => 
    affectedDocumentTypes.includes(rule.document_type)
  ).length;
  const daysUntilDeadline = Math.floor((complianceDeadline.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));

  if (affectedRuleCount === 0) {
    console.warn("この法令改正による直接的な影響は検出されませんでした。念のため手動確認を推奨します。");
  }

  let impactLevel = "low";
  let priority = 3;
  let requiredResponseDays = 60;

  if (hasSubsidyRequirementChange && (affectedRuleCount >= 10 || daysUntilDeadline < 30)) {
    impactLevel = "high";
    priority = 1;
    requiredResponseDays = 14;
  } else if (hasSubsidyRequirementChange && (affectedRuleCount >= 5 || daysUntilDeadline < 60)) {
    impactLevel = "medium";
    priority = 2;
    requiredResponseDays = 30;
  }

  const riskAssessment = impactLevel === "high" ? "法令違反リスク高" : 
                        impactLevel === "medium" ? "業務遅延リスク中" : "影響軽微";

  return { impactLevel, priority, requiredResponseDays, affectedRuleCount, riskAssessment };
}

interface MigrationResult {
  migratedCount: number;
  skippedCount: number;
  errorCount: number;
  updatedRoutes: RouteUpdate[];
}

function isInMigrationScope(document: Document, migrationScope: string): boolean {
  const docType = document.type || document.documentType || '';
  const title = document.title || '';
  const content = document.content || '';
  
  if (migrationScope === '補助金関連書類' || migrationScope === '補助金関連') {
    return docType.includes('補助金') || 
           title.includes('補助金') || 
           title.includes('科研費') || 
           title.includes('設備整備費') || 
           content.includes('補助金') || 
           content.includes('科研費') || 
           content.includes('設備整備費');
  }
  
  return true;
}

function applyNewRulesInternal(document: Document, newClassificationRules: ClassificationRule[]): { processingRoute: string } {
  const docType = document.type || document.documentType || '';
  const title = document.title || '';
  const content = document.content || '';
  
  // 補助金関連キーワードをチェック
  const hasSubsidyKeywords = title.includes('科研費') || 
                            title.includes('設備整備費') || 
                            content.includes('科研費') || 
                            content.includes('設備整備費') ||
                            content.includes('科学研究費補助金') ||
                            content.includes('設備整備費補助金');
  
  // 補助金関連キーワードがある場合はhybridルートに
  if (hasSubsidyKeywords) {
    return { processingRoute: 'hybrid' };
  }
  
  // 文書タイプに基づく分類
  for (const rule of newClassificationRules) {
    if (docType === rule.documentType) {
      return { processingRoute: rule.processingRoute };
    }
  }
  
  return { processingRoute: document.current_processing_route };
}

export function migrateExistingDataToNewClassification(
  newClassificationRules: ClassificationRule[], 
  existingDocuments: Document[], 
  migrationScope: string
): { migratedCount: number; skippedCount: number; errorCount: number; updatedRoutes: RouteUpdate[] } {
  if (newClassificationRules.length === 0) {
    throw new Error('法令改正に基づく新しい分類基準が設定されていません。分類基準を確認してください。');
  }
  
  const targetDocuments = existingDocuments.filter(doc => isInMigrationScope(doc, migrationScope));
  let migratedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;
  const updatedRoutes: RouteUpdate[] = [];
  
  for (const document of targetDocuments) {
    try {
      const newClassification = applyNewRulesInternal(document, newClassificationRules);
      if (newClassification.processingRoute !== document.current_processing_route) {
        updatedRoutes.push({
          documentId: document.id, 
          oldRoute: document.current_processing_route, 
          newRoute: newClassification.processingRoute
        });
        migratedCount++;
      } else {
        skippedCount++;
      }
    } catch (error) {
      errorCount++;
    }
  }
  
  return { migratedCount, skippedCount, errorCount, updatedRoutes };
}

export function setApproverAuthorityLevel(
  documentType: string,
  subsidyRelated: boolean,
  paperStorageRequired: boolean,
  applicantDepartment: string,
  budgetAmount: number
): { requiredAuthorityLevel: string; approverRoles: string[]; escalationRequired: boolean } {
  if (budgetAmount < 0) {
    throw new Error("予算金額は0以上の値を入力してください");
  }
  
  if (!applicantDepartment || applicantDepartment.trim() === "") {
    throw new Error("申請者の所属部署を選択してください");
  }

  const isHighBudget = budgetAmount > 5000000;
  const isVeryHighBudget = budgetAmount > 10000000;
  const needsHighAuthority = subsidyRelated || isHighBudget;
  const requiredAuthorityLevel = needsHighAuthority ? "department_head" : "section_chief";
  const approverRoles = [requiredAuthorityLevel];
  
  if (paperStorageRequired) {
    approverRoles.push("administrative_director");
  }
  
  const escalationRequired = isVeryHighBudget;
  
  return { requiredAuthorityLevel, approverRoles, escalationRequired };
}

function getApproversByLevel(approvalLevel: string, applicantDepartment: string): string[] {
  switch (approvalLevel) {
    case "課長承認":
      return ["課長"];
    case "部長承認":
      return ["部長"];
    case "理事承認":
      return ["部長", "理事"];
    default:
      return [];
  }
}

export function determineApprovalHierarchy(
  applicationAmount: number,
  documentType: string,
  applicantDepartment: string
): { approvalLevel: string; approvers: string[]; estimatedDays: number; requiresPaperApproval: boolean } {
  if (applicationAmount <= 0) {
    throw new Error("申請金額は1円以上で入力してください");
  }
  
  if (!applicantDepartment || applicantDepartment.trim() === "") {
    throw new Error("承認ルート設定のため、所属部署を入力してください");
  }
  
  if (applicationAmount > 100000000) {
    console.warn("高額申請のため、理事会での特別承認が必要になる可能性があります");
  }

  let approvalLevel = "";
  let estimatedDays = 0;
  let requiresPaperApproval = false;
  
  if (documentType.includes("補助金")) {
    if (applicationAmount >= 1000000) {
      approvalLevel = "理事承認";
      estimatedDays = 7;
    } else {
      approvalLevel = "部長承認";
      estimatedDays = 5;
    }
    requiresPaperApproval = true;
  } else {
    if (applicationAmount < 100000) {
      approvalLevel = "課長承認";
      estimatedDays = 3;
    } else if (applicationAmount < 1000000) {
      approvalLevel = "部長承認";
      estimatedDays = 5;
    } else {
      approvalLevel = "理事承認";
      estimatedDays = 7;
    }
  }
  
  const approvers = getApproversByLevel(approvalLevel, applicantDepartment);
  return { approvalLevel, approvers, estimatedDays, requiresPaperApproval };
}

function addBusinessDays(startDate: Date, businessDays: number): Date {
  const result = new Date(startDate.getTime());
  let daysToAdd = businessDays;
  
  // 小数点がある場合は時間も計算
  const wholeDays = Math.floor(daysToAdd);
  const fractionalDay = daysToAdd - wholeDays;
  
  let addedDays = 0;
  while (addedDays < wholeDays) {
    result.setDate(result.getDate() + 1);
    const dayOfWeek = result.getDay();
    // 土曜日(6)と日曜日(0)以外は営業日
    if (dayOfWeek !== 0 && dayOfWeek !== 6) {
      addedDays++;
    }
  }
  
  // 小数部分を時間として追加
  if (fractionalDay > 0) {
    const hoursToAdd = fractionalDay * 24;
    result.setHours(result.getHours() + hoursToAdd);
  }
  
  return result;
}

export function setApprovalDeadline(
  documentType: string,
  subsidyRelated: boolean,
  urgencyLevel: string,
  submissionDate: Date
): { deadlineDate: Date; businessDays: number; notificationSchedule: string[] } {
  // 提出日が未来の日付でないかチェック
  const now = new Date();
  if (submissionDate > now) {
    throw new Error("提出日は現在日時以前である必要があります");
  }
  
  // 緊急度レベルの検証
  const validUrgencyLevels = ["高", "標準", "低"];
  if (!validUrgencyLevels.includes(urgencyLevel)) {
    throw new Error("緊急度は「高」「標準」「低」のいずれかを選択してください");
  }
  
  let baseDays = subsidyRelated ? 5 : 3;
  
  if (urgencyLevel === "高") {
    baseDays = baseDays / 2;
  } else if (urgencyLevel === "低") {
    baseDays = baseDays * 1.5;
  }
  
  const deadlineDate = addBusinessDays(submissionDate, baseDays);
  const businessDays = baseDays;
  const notificationSchedule = ["2日前", "当日"];
  
  return { deadlineDate, businessDays, notificationSchedule };
}
