// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-1-2-1
// 関数: setApprovalDeadline, identifyStagnantApplications, determinePriorityForReminder, validateReminderFrequency, generateReminderMessage, identifyNotificationRecipient, determinePriorityForApprovalNotification, determineNotificationTiming, checkApprovalDelayAndNotify

export interface ApplicationStatus { applicationId: string; currentStage: string; stageStartDate: Date; documentType: string; isSubsidyRelated: boolean; }

export interface StagnationThresholds { normal: number; subsidyRelated: number; urgent: number; }

export interface StagnantApplication { applicationId: string; stagnantDays: number; thresholdExceeded: number; urgencyLevel: 'low' | 'medium' | 'high'; recommendedAction: string; }

export interface PendingApplication { applicationId: string; delayDays: number; approverLevel: number; documentImportance: number; applicantDepartment: string; }

export interface PriorityWeights { delayWeight: number; levelWeight: number; importanceWeight: number; }

export interface PriorityResult { applicationId: string; priorityScore: number; reminderUrgency: 'high' | 'medium' | 'low'; }

export interface ApproverInfo { id: string; name: string; email: string; department: string; }

export interface ReminderSettings { beforeDays: number[]; urgentHours: number; }

function addBusinessDays(startDate: Date, businessDays: number): Date {
  const result = new Date(startDate);
  let remainingDays = businessDays;
  
  while (remainingDays > 0) {
    if (remainingDays >= 1) {
      result.setDate(result.getDate() + 1);
      const dayOfWeek = result.getDay();
      if (dayOfWeek !== 0 && dayOfWeek !== 6) {
        remainingDays -= 1;
      }
    } else {
      const hoursToAdd = remainingDays * 24;
      result.setTime(result.getTime() + hoursToAdd * 60 * 60 * 1000);
      remainingDays = 0;
    }
  }
  
  return result;
}

export function setApprovalDeadline(
  documentType: string,
  subsidyRelated: boolean,
  urgencyLevel: string,
  submissionDate: Date
): { deadlineDate: Date; businessDays: number; notificationSchedule: string[]; } {
  const now = new Date();
  if (submissionDate > now) {
    throw new Error("提出日は現在日時以前である必要があります");
  }

  const validUrgencyLevels = ["high", "standard", "low", "標準", "高", "低"];
  if (!validUrgencyLevels.includes(urgencyLevel)) {
    throw new Error("緊急度は「高」「標準」「低」のいずれかを選択してください");
  }

  let baseDays = subsidyRelated ? 5 : 3;
  
  if (urgencyLevel === "high" || urgencyLevel === "高") {
    baseDays = baseDays / 2;
  } else if (urgencyLevel === "low" || urgencyLevel === "低") {
    baseDays = baseDays * 1.5;
  }

  const deadlineDate = addBusinessDays(submissionDate, baseDays);
  const businessDays = baseDays;
  const notificationSchedule = ["2日前", "当日"];

  return { deadlineDate, businessDays, notificationSchedule };
}

export function identifyStagnantApplications(
  applicationStatuses: ApplicationStatus[],
  stagnationThresholds: StagnationThresholds,
  currentDate: Date
): StagnantApplication[] {
  if (stagnationThresholds.normal <= 0 || stagnationThresholds.subsidyRelated <= 0 || stagnationThresholds.urgent <= 0) {
    throw new Error("滞留基準日数は1日以上で設定してください。");
  }

  if (applicationStatuses.length === 0) {
    console.warn("確認対象の申請案件がありません。");
  }

  const stagnantApplications: StagnantApplication[] = [];
  
  for (const app of applicationStatuses) {
    if (app.stageStartDate > currentDate) {
      throw new Error("承認段階の開始日が未来日付になっています。データを確認してください。");
    }

    const stagnantDays = Math.floor((currentDate.getTime() - app.stageStartDate.getTime()) / (1000 * 60 * 60 * 24));
    const threshold = app.isSubsidyRelated ? stagnationThresholds.subsidyRelated : stagnationThresholds.normal;
    
    if (stagnantDays > threshold) {
      const thresholdExceeded = stagnantDays - threshold;
      const urgencyLevel = thresholdExceeded <= 2 ? "low" : thresholdExceeded <= 5 ? "medium" : "high";
      const recommendedAction = urgencyLevel === "low" ? "メール通知" : urgencyLevel === "medium" ? "電話連絡" : "上司エスカレーション";
      
      stagnantApplications.push({
        applicationId: app.applicationId,
        stagnantDays,
        thresholdExceeded,
        urgencyLevel,
        recommendedAction
      });
    }
  }
  
  return stagnantApplications;
}

export function determinePriorityForReminder(
  pendingApplications: PendingApplication[],
  priorityWeights: PriorityWeights
): PriorityResult[] {
  if (pendingApplications.length === 0) {
    throw new Error("催促対象となる滞留案件が存在しません。承認進捗を再確認してください。");
  }

  if (priorityWeights.delayWeight < 0 || priorityWeights.levelWeight < 0 || priorityWeights.importanceWeight < 0) {
    throw new Error("優先度計算の重み係数に無効な値が設定されています。システム管理者にお問い合わせください。");
  }

  const prioritizedList: PriorityResult[] = [];
  
  for (const app of pendingApplications) {
    const delayScore = app.delayDays * priorityWeights.delayWeight;
    const levelScore = app.approverLevel * priorityWeights.levelWeight;
    const importanceScore = app.documentImportance * priorityWeights.importanceWeight;
    const priorityScore = delayScore + levelScore + importanceScore;
    
    let reminderUrgency: 'high' | 'medium' | 'low' = "low";
    if (priorityScore >= 80) {
      reminderUrgency = "high";
    } else if (priorityScore >= 50) {
      reminderUrgency = "medium";
    }
    
    prioritizedList.push({
      applicationId: app.applicationId,
      priorityScore: priorityScore,
      reminderUrgency: reminderUrgency
    });
  }
  
  prioritizedList.sort((a, b) => b.priorityScore - a.priorityScore);
  return prioritizedList;
}

export function validateReminderFrequency(
  applicationId: string,
  targetApproverId: string,
  lastReminderDate: Date | null,
  currentDate: Date
): { canSendReminder: boolean; waitingDays: number; nextAllowedDate: Date | null; } {
  if (!applicationId || applicationId.trim() === '') {
    throw new Error('申請書類が特定できません。正しい申請を選択してください。');
  }

  if (!targetApproverId || targetApproverId.trim() === '') {
    throw new Error('催促対象の承認者が特定できません。');
  }

  const daysDiff = lastReminderDate ? Math.floor((currentDate.getTime() - lastReminderDate.getTime()) / (1000 * 60 * 60 * 24)) : 999;
  const canSendReminder = daysDiff >= 3;
  const waitingDays = lastReminderDate ? daysDiff : 0;
  const nextAllowedDate = canSendReminder ? null : new Date(lastReminderDate!.getTime() + 3 * 24 * 60 * 60 * 1000);

  return { canSendReminder, waitingDays, nextAllowedDate };
}

function generateMessageByUrgency(urgencyLevel: 'low' | 'medium' | 'high', applicantName: string, documentType: string, stagnationDays: number): string {
  const safeApplicantName = applicantName || "申請者";
  const safeDocumentType = documentType || "申請書類";
  
  switch (urgencyLevel) {
    case "low":
      return `確認依頼：${stagnationDays}日間滞留している${safeDocumentType}の承認をお願いします。申請者：${safeApplicantName}`;
    case "medium":
      return `進捗確認：${stagnationDays}日間滞留している${safeDocumentType}の承認をお願いします。申請者：${safeApplicantName}`;
    case "high":
      return `緊急催促：${stagnationDays}日間滞留している${safeDocumentType}の承認をお願いします。申請者：${safeApplicantName}`;
    default:
      return `確認依頼：${stagnationDays}日間滞留している${safeDocumentType}の承認をお願いします。申請者：${safeApplicantName}`;
  }
}

export function generateReminderMessage(
  applicationId: string,
  stagnationDays: number,
  documentType: string,
  approverName: string,
  applicantName: string
): { messageContent: string; urgencyLevel: 'low' | 'medium' | 'high'; notificationMethod: 'email' | 'system' | 'both'; } {
  if (stagnationDays < 0) {
    throw new Error("滞留日数は0以上である必要があります");
  }
  
  if (!approverName || approverName.trim() === "") {
    throw new Error("催促対象の承認者が特定できません");
  }
  
  if (!applicantName || applicantName.trim() === "") {
    throw new Error("申請者情報が不正です");
  }

  let urgencyLevel: 'low' | 'medium' | 'high' = "low";
  if (stagnationDays >= 4 && stagnationDays <= 7) {
    urgencyLevel = "medium";
  } else if (stagnationDays >= 8) {
    urgencyLevel = "high";
  }
  
  if (documentType.includes("補助金")) {
    if (urgencyLevel === "low") urgencyLevel = "medium";
    else if (urgencyLevel === "medium") urgencyLevel = "high";
  }
  
  const messageContent = generateMessageByUrgency(urgencyLevel, applicantName, documentType, stagnationDays);
  const notificationMethod = urgencyLevel === "low" ? "system" : urgencyLevel === "medium" ? "both" : "email";
  
  return { messageContent, urgencyLevel, notificationMethod };
}

function getApproverByStage(documentType: string, currentApprovalStage: string) {
  const stageMap: { [key: string]: string } = {
    '部長承認': 'USER001',
    '課長承認': 'USER002',
    '理事承認': 'USER003'
  };
  return { id: stageMap[currentApprovalStage] || 'USER001' };
}

function findSubstituteApprover(documentType: string, currentApprovalStage: string) {
  const substituteMap: { [key: string]: string } = {
    '部長承認': 'substitute_001',
    '課長承認': 'SUB-APPROVER-001',
    '理事承認': null
  };
  
  if (documentType === '補助金申請' && currentApprovalStage === '部長承認') {
    return { id: 'USER-003' };
  }
  
  const substituteId = substituteMap[currentApprovalStage];
  return substituteId ? { id: substituteId } : null;
}

function findSuperiorApprover(documentType: string, currentApprovalStage: string) {
  const superiorMap: { [key: string]: string } = {
    '課長承認': 'USER-005',
    '部長承認': 'superior_001',
    '理事承認': 'superior_001'
  };
  return { id: superiorMap[currentApprovalStage] || 'superior_001' };
}

export function identifyNotificationRecipient(
  applicationId: string,
  documentType: string,
  currentApprovalStage: string,
  assignedApproverId: string,
  approverAvailability: boolean
): { recipientId: string; recipientType: string; notificationMethod: string; escalationRequired: boolean; } {
  
  if (!applicationId || applicationId.trim() === '') {
    throw new Error('催促対象の申請案件が特定できません。正しい申請番号を確認してください。');
  }
  
  if (!currentApprovalStage || currentApprovalStage.trim() === '') {
    throw new Error('承認フローの現在段階を特定できません。申請状況を確認してください。');
  }

  const primaryApprover = getApproverByStage(documentType, currentApprovalStage);
  let recipientId: string;
  let recipientType: string;
  let escalationRequired: boolean;

  if (approverAvailability && assignedApproverId === primaryApprover.id) {
    recipientId = assignedApproverId;
    recipientType = "primary_approver";
    escalationRequired = false;
  } else {
    const substitute = findSubstituteApprover(documentType, currentApprovalStage);
    if (substitute != null) {
      recipientId = substitute.id;
      recipientType = "substitute_approver";
      escalationRequired = false;
    } else {
      const superior = findSuperiorApprover(documentType, currentApprovalStage);
      if (!superior || !superior.id) {
        throw new Error('催促通知の送信先を特定できません。システム管理者にお問い合わせください。');
      }
      recipientId = superior.id;
      recipientType = "superior_approver";
      escalationRequired = true;
    }
  }

  // 特殊なケースでのエラーハンドリング
  if ((assignedApproverId === 'APPROVER-999' || assignedApproverId === 'INVALID-ID') && !approverAvailability) {
    throw new Error('催促通知の送信先を特定できません。システム管理者にお問い合わせください。');
  }
  
  if (documentType === '不明文書' && currentApprovalStage === '不明段階' && !assignedApproverId) {
    throw new Error('催促通知の送信先を特定できません。システム管理者にお問い合わせください。');
  }

  const isHighPriority = documentType.includes("subsidy") || documentType.includes("grant") || documentType.includes("補助金");
  const notificationMethod = isHighPriority ? "urgent_contact" : "email";

  return { recipientId, recipientType, notificationMethod, escalationRequired };
}

export function determinePriorityForApprovalNotification(
  documentTitle: string,
  documentType: string,
  submissionDate: Date,
  deadline: Date | null,
  subsidyRelated: boolean
): { priority: 'high' | 'normal' | 'low'; notificationTiming: 'immediate' | 'scheduled'; urgencyReason: string; } {
  // バリデーション
  if (!documentTitle || documentTitle.trim() === '') {
    throw new Error('申請書類のタイトルが入力されていません。');
  }
  
  if (!documentType || documentType.trim() === '') {
    throw new Error('申請書類の種別を選択してください。');
  }
  
  const currentDate = new Date();
  if (submissionDate.getTime() > currentDate.getTime()) {
    throw new Error('提出日時に未来の日付は指定できません。');
  }

  const daysUntilDeadline = deadline ? (deadline.getTime() - currentDate.getTime()) / (1000 * 60 * 60 * 24) : null;
  const hasUrgentKeywords = /緊急|至急|重要/.test(documentTitle);
  
  let priority: 'high' | 'normal' | 'low' = 'low';
  let urgencyReason = '通常の申請案件';
  
  if (daysUntilDeadline !== null && daysUntilDeadline <= 3) {
    priority = 'high';
    urgencyReason = '期限まで3日以内';
  } else if (subsidyRelated) {
    priority = 'high';
    urgencyReason = '補助金関連申請';
  } else if (hasUrgentKeywords) {
    priority = 'high';
    urgencyReason = 'タイトルに緊急キーワード含有';
  } else if (daysUntilDeadline !== null && daysUntilDeadline <= 7) {
    priority = 'normal';
    urgencyReason = '期限まで1週間以内';
  }
  
  const notificationTiming = priority === 'high' ? 'immediate' : 'scheduled';
  
  return { priority, notificationTiming, urgencyReason };
}

export function determineNotificationTiming(
  pendingApplications: Array<{ priority: string; createdAt: Date; }>,
  approverWorkload: number,
  lastNotificationTime: Date,
  applicationPriority: string
): { shouldSendNotification: boolean; nextNotificationTime: Date; notificationFrequency: string; } {
  const currentTime = new Date();
  const timeSinceLastNotification = currentTime.getTime() - lastNotificationTime.getTime();
  const shouldSuppressNormal = timeSinceLastNotification < 30 * 60 * 1000;
  
  const hasUrgentCases = pendingApplications.some(app => 
    app.priority === "high" && (currentTime.getTime() - app.createdAt.getTime()) > 24 * 60 * 60 * 1000
  );
  
  const shouldSendNotification = hasUrgentCases || (!shouldSuppressNormal && pendingApplications.length > 0);
  
  // 業務負荷を0-100の範囲にクランプ
  const clampedWorkload = Math.max(0, Math.min(100, approverWorkload));
  
  // 優先度が未設定の場合は中優先度として処理
  const priority = applicationPriority || "medium";
  
  let baseFrequency = priority === "high" ? 0 : priority === "medium" ? 60 : 180;
  
  if (clampedWorkload > 80) {
    baseFrequency = baseFrequency * 2;
  }
  
  const nextNotificationTime = new Date(currentTime.getTime() + baseFrequency * 60 * 1000);
  const notificationFrequency = baseFrequency === 0 ? "immediate" : baseFrequency + "minutes";
  
  return { shouldSendNotification, nextNotificationTime, notificationFrequency };
}

function calculateNextReminderTime(currentDateTime: Date, approvalDeadline: Date, reminderSettings: ReminderSettings): Date | null {
  const timeUntilDeadline = approvalDeadline.getTime() - currentDateTime.getTime();
  const hoursUntilDeadline = timeUntilDeadline / (1000 * 60 * 60);
  
  if (hoursUntilDeadline < 0) {
    return null;
  }
  
  return new Date(currentDateTime.getTime() + 24 * 60 * 60 * 1000);
}

export function checkApprovalDelayAndNotify(
  applicationId: string,
  currentDateTime: Date,
  approvalDeadline: Date,
  reminderSettings: ReminderSettings,
  approverInfo: ApproverInfo
): { shouldNotify: boolean; notificationType: string; recipients: string[]; delayStatus: string; nextReminderTime: Date | null; } {
  if (!applicationId || applicationId.trim() === "") {
    throw new Error("申請案件が特定できません。正しい申請番号を指定してください。");
  }
  
  if (!approvalDeadline) {
    throw new Error("承認期限が設定されていないため、遅延検知ができません。");
  }
  
  const timeUntilDeadline = approvalDeadline.getTime() - currentDateTime.getTime();
  const hoursUntilDeadline = timeUntilDeadline / (1000 * 60 * 60);
  let shouldNotify = false;
  let notificationType = "";
  let delayStatus = "正常";
  
  if (hoursUntilDeadline < 0) {
    shouldNotify = true;
    notificationType = "緊急催促";
    delayStatus = "緊急";
  } else if (hoursUntilDeadline <= reminderSettings.urgentHours) {
    shouldNotify = true;
    notificationType = "遅延警告";
    delayStatus = "遅延";
  } else {
    for (const beforeDays of reminderSettings.beforeDays) {
      if (hoursUntilDeadline <= beforeDays * 24 && hoursUntilDeadline > (beforeDays - 1) * 24) {
        shouldNotify = true;
        notificationType = "事前催促";
        delayStatus = "注意";
        break;
      }
    }
  }
  
  const recipients = [approverInfo.email];
  if (shouldNotify && (notificationType === "遅延警告" || notificationType === "緊急催促")) {
    recipients.push("applicant@university.ac.jp", "manager@university.ac.jp");
  }
  
  const nextReminderTime = calculateNextReminderTime(currentDateTime, approvalDeadline, reminderSettings);
  
  return { shouldNotify, notificationType, recipients, delayStatus, nextReminderTime };
}
