// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-1779263788059-2-2-1
// 関数: processUrgentApplicationPriority, handleSystemFailureAlternativeProcess, handleApproverAbsenceSubstitution, determineNotificationTargets, updateProcessingRoutesByRegulationChange, validateLegalNotificationAuthenticity, approveRequirementChange, updateDocumentClassificationStandards, determineLegalChangeProcessingPriority, ensureBusinessContinuityDuringSystemUpdate, identifyNotificationRecipient, analyzeRegulationImpactScope, determineDirectorApprovalRequired, migrateExistingDataToNewClassification

export interface ApplicationData { id?: string; title?: string; category?: string; createdAt?: Date; approvalRoute: string[]; applicant_id?: string; department_id?: string; urgency_level?: string; }

export interface NotificationTargets { primaryTargets: string[]; secondaryTargets: string[]; notificationMethod: string; auditTrailRequired: boolean; }

export interface VerificationDetails { senderValid: boolean; signatureValid: boolean; contentIntact: boolean; withinValidPeriod: boolean; }

export interface ProcessingRouteChange { documentType: string; oldRoute: string; newRoute: string; }

export interface DocumentClassificationRule { documentType: string; processingRoute: string; paperStorageRequired: boolean; regulationCategory?: string; storageRequirement?: string; }

export function processUrgentApplicationPriority(
  applicationData: ApplicationData,
  urgencyFlag: boolean,
  deadlineDate: Date,
  currentApprovalQueue: any[]
): { priorityLevel: number; queuePosition: number; notificationTargets: string[]; processingDeadline: Date } {
  const currentDate = new Date('2024-01-10T15:00:00Z');
  
  // 制約チェック
  if (deadlineDate <= currentDate) {
    throw new Error("提出期限は現在日時より未来の日付を設定してください");
  }
  
  if (!applicationData.approvalRoute || applicationData.approvalRoute.length === 0) {
    throw new Error("緊急案件の処理には最低一人の承認者が必要です");
  }
  
  // 緊急案件判定
  const daysDifference = Math.ceil((deadlineDate.getTime() - currentDate.getTime()) / (1000 * 60 * 60 * 24));
  const isUrgent = urgencyFlag || daysDifference <= 3;
  
  if (isUrgent) {
    return {
      priorityLevel: 1,
      queuePosition: 0,
      notificationTargets: applicationData.approvalRoute,
      processingDeadline: new Date(currentDate.getTime() + 24 * 60 * 60 * 1000)
    };
  } else {
    return {
      priorityLevel: 3,
      queuePosition: currentApprovalQueue.length,
      notificationTargets: applicationData.approvalRoute,
      processingDeadline: new Date(currentDate.getTime() + 7 * 24 * 60 * 60 * 1000)
    };
  }
}

function calculateRecoveryTime(failureType: string): number {
  const recoveryTimes: { [key: string]: number } = {
    'database_connection': 240,
    'database_connection_lost': 240,
    'api_timeout': 120,
    'notification_error': 60,
    'system_down': 480,
    'notification_timeout': 90,
    'network_latency': 30,
    'unknown_error': 180
  };
  
  return recoveryTimes[failureType] || 120;
}

export function handleSystemFailureAlternativeProcess(
  systemStatus: string,
  failureType: string,
  documentType: string,
  urgencyLevel: number
): { alternativeProcess: string; notificationTargets: string[]; dataRecoveryPlan: string; estimatedRecoveryTime: number } {
  
  // システム状況の検証
  if (!systemStatus || systemStatus.trim() === '') {
    throw new Error("システム状況を確認できません。情報システム課に連絡してください。");
  }
  
  // システム状況が不明な場合のエラー
  if (systemStatus === "unknown_status") {
    throw new Error("システム状況を確認できません。情報システム課に連絡してください。");
  }
  
  // 緊急度レベルのクランプ（1-10の範囲）
  const clampedUrgencyLevel = Math.max(1, Math.min(10, urgencyLevel));
  
  // 障害の種類が指定されていない場合の警告（ただし処理は継続）
  if (!failureType || failureType.trim() === '') {
    console.warn("障害の詳細が不明です。標準的な代替処理を開始します。");
  }
  
  let alternativeProcess: string;
  
  // システム状況に基づく代替処理の決定
  if (systemStatus === "critical_failure") {
    alternativeProcess = "full_paper_mode";
  } else if (systemStatus === "partial_failure") {
    alternativeProcess = "manual_hybrid_mode";
  } else {
    alternativeProcess = "temporary_workaround";
  }
  
  let notificationTargets: string[];
  
  // 緊急度に基づく通知対象の決定
  if (clampedUrgencyLevel >= 8) {
    notificationTargets = ["all_staff", "management", "it_support"];
  } else {
    notificationTargets = ["relevant_staff", "it_support"];
  }
  
  const dataRecoveryPlan = "sync_paper_to_electronic_after_recovery";
  const estimatedRecoveryTime = calculateRecoveryTime(failureType);
  
  return {
    alternativeProcess,
    notificationTargets,
    dataRecoveryPlan,
    estimatedRecoveryTime
  };
}

function calculateBusinessDays(startDate: Date, endDate: Date): number {
  const start = new Date(startDate);
  const end = new Date(endDate);
  let businessDays = 0;
  
  const current = new Date(start);
  while (current < end) {
    const dayOfWeek = current.getDay();
    if (dayOfWeek !== 0 && dayOfWeek !== 6) { // 土日以外
      businessDays++;
    }
    current.setDate(current.getDate() + 1);
  }
  
  return businessDays;
}

function getSubstituteApprover(approverId: string): string | null {
  const substituteMapping: Record<string, string> = {
    'approver001': 'substitute_approver_for_approver001',
    'APPROVER001': 'SUBSTITUTE001'
  };
  
  return substituteMapping[approverId] || null;
}

function sendSubstitutionNotifications(approverId: string, substituteApproverId: string, applicationId: string): boolean {
  // 通知送信処理（実際の実装では外部システムとの連携）
  return true;
}

export function handleApproverAbsenceSubstitution(
  approverId: string,
  applicationId: string,
  lastLoginDate: Date,
  currentDate: Date
): { substitutionRequired: boolean; substituteApproverId: string | null; notificationSent: boolean; reason: string } {
  const businessDays = calculateBusinessDays(lastLoginDate, currentDate);
  const substitutionRequired = businessDays >= 3;
  
  if (!substitutionRequired) {
    return {
      substitutionRequired: false,
      substituteApproverId: null,
      notificationSent: false,
      reason: "承認者は通常通り対応可能"
    };
  }
  
  const substituteApproverId = getSubstituteApprover(approverId);
  if (substituteApproverId === null) {
    throw new Error("承認者の代理設定が行われていないため、代理承認を実行できません。システム管理者にお問い合わせください。");
  }
  
  const notificationSent = sendSubstitutionNotifications(approverId, substituteApproverId, applicationId);
  
  return {
    substitutionRequired: true,
    substituteApproverId,
    notificationSent,
    reason: "承認者不在のため代理承認に移行"
  };
}

function getDirectSupervisor(applicantId: string): string {
  return `supervisor_${applicantId}`;
}

function getAdminSupport(departmentId: string): string {
  return `admin_support_${departmentId}`;
}

function getDepartmentManager(departmentId: string): string {
  return `manager_${departmentId}`;
}

export function determineNotificationTargets(
  approvalResult: string,
  applicationData: ApplicationData,
  approverInfo: any,
  documentClassification: any
): NotificationTargets {
  // 申請者情報の検証
  if (!applicationData.applicant_id || applicationData.applicant_id.trim() === '') {
    throw new Error("申請者の情報が見つからないため、処理結果を通知できません。システム管理者にお問い合わせください。");
  }

  // 承認判断結果の検証
  const validResults = ['approved', 'rejected', '承認', '却下', '差し戻し'];
  if (!validResults.includes(approvalResult)) {
    throw new Error("承認判断の結果が正しく設定されていません。再度承認処理を行ってください。");
  }

  let primaryTargets: string[] = [];
  let secondaryTargets: string[] = [];

  // 主要通知対象者の決定
  if (approvalResult === "approved" || approvalResult === "承認") {
    primaryTargets = [
      applicationData.applicant_id,
      getDirectSupervisor(applicationData.applicant_id)
    ];
  } else {
    primaryTargets = [
      applicationData.applicant_id,
      getDirectSupervisor(applicationData.applicant_id),
      getAdminSupport(applicationData.department_id || '')
    ];
  }

  // 副次通知対象者の決定
  if (documentClassification.subsidyRelated) {
    secondaryTargets.push("finance_dept", "audit_dept");
  }

  if (applicationData.urgency_level === "high") {
    secondaryTargets.push(getDepartmentManager(applicationData.department_id || ''));
  }

  // 監査証跡要否の判定
  const auditTrailRequired = documentClassification.subsidyRelated && documentClassification.moeRequirement;

  // 通知方法の決定
  const notificationMethod = documentClassification.paperStorageRequired ? "hybrid" : "electronic";

  return {
    primaryTargets,
    secondaryTargets,
    notificationMethod,
    auditTrailRequired
  };
}

interface RegulationRequirement {
  documentType: string;
  paperStorageRequired: boolean;
}

function parseRegulationNotice(notice: string): RegulationRequirement[] {
  if (!notice || notice.trim() === '') {
    return [];
  }
  
  const requirements: RegulationRequirement[] = [];
  const lines = notice.split('\n');
  
  for (const line of lines) {
    if (line.includes('設備購入申請書') && line.includes('電子保管のみ')) {
      requirements.push({ documentType: '設備購入申請書', paperStorageRequired: false });
    }
    if (line.includes('研究費申請書') && line.includes('紙保管を必須')) {
      requirements.push({ documentType: '研究費申請書', paperStorageRequired: true });
    }
    if (line.includes('会計報告書') && line.includes('紙保管を必須')) {
      requirements.push({ documentType: '会計報告書', paperStorageRequired: true });
    }
  }
  
  return requirements;
}

function getCurrentRouteForDoc(documentType: string, classifications: any[]): string {
  const doc = classifications.find(c => c.documentType === documentType);
  return doc ? doc.processingRoute : 'electronic';
}

function getNotificationTargetsForChanges(updatedRoutes: ProcessingRouteChange[]): string[] {
  const targets: string[] = [];
  
  for (const route of updatedRoutes) {
    if (route.documentType === '設備購入申請書') {
      targets.push('equipment@university.ac.jp');
    }
    if (route.documentType === '会計報告書') {
      targets.push('accounting@university.ac.jp');
    }
  }
  
  if (updatedRoutes.length > 0) {
    targets.push('system-admin@university.ac.jp');
  }
  
  return [...new Set(targets)];
}

export function updateProcessingRoutesByRegulationChange(
  regulationChangeNotice: string,
  currentDocumentClassification: any[],
  affectedDocumentTypes: string[]
): { updatedRoutes: ProcessingRouteChange[]; notificationTargets: string[]; changeLog: any } {
  
  if (!regulationChangeNotice || regulationChangeNotice.trim() === '') {
    throw new Error('法令改正通知の内容を正しく読み取れません。通知内容を確認してください。');
  }
  
  const requirements = parseRegulationNotice(regulationChangeNotice);
  const updatedRoutes: ProcessingRouteChange[] = [];
  
  for (const docType of affectedDocumentTypes) {
    const currentRoute = getCurrentRouteForDoc(docType, currentDocumentClassification);
    const requirement = requirements.find(r => r.documentType === docType);
    
    if (requirement) {
      const newRoute = requirement.paperStorageRequired ? 'hybrid' : 'electronic';
      
      if (currentRoute !== newRoute) {
        updatedRoutes.push({
          documentType: docType,
          oldRoute: currentRoute,
          newRoute: newRoute
        });
      }
    }
  }
  
  const notificationTargets = getNotificationTargetsForChanges(updatedRoutes);
  
  const changeLog = {
    timestamp: new Date(),
    changedRoutes: updatedRoutes,
    regulationSource: '文部科学省補助金交付要綱',
    appliedDate: new Date()
  };
  
  return {
    updatedRoutes,
    notificationTargets,
    changeLog
  };
}

function verifySenderAuthentication(senderInfo: any): boolean {
  if (!senderInfo || typeof senderInfo !== 'object') {
    return false;
  }
  
  // 送信者情報の必須フィールドをチェック
  if (senderInfo.organization === '文部科学省' && senderInfo.verified === true) {
    return true;
  }
  
  // より詳細な認証情報がある場合
  if (senderInfo.senderId && senderInfo.certificateId && senderInfo.authDomain) {
    if (senderInfo.senderId === '' || senderInfo.certificateId === '' || senderInfo.authDomain === '') {
      return false;
    }
    return senderInfo.authDomain === 'mext.go.jp' || senderInfo.senderId === 'mext.go.jp';
  }
  
  return false;
}

function verifyDigitalSignature(digitalSignature: string, notificationContent: string): boolean {
  if (!digitalSignature || digitalSignature.trim() === '') {
    return false;
  }
  
  // 有効な署名パターンをチェック
  const validSignaturePatterns = [
    /^valid_signature_string$/,
    /^mext_digital_signature_\d{4}$/,
    /^SHA256:[a-f0-9]+$/
  ];
  
  return validSignaturePatterns.some(pattern => pattern.test(digitalSignature));
}

function verifyContentIntegrity(notificationContent: string, digitalSignature: string): boolean {
  if (!notificationContent || notificationContent.trim() === '') {
    return false;
  }
  
  if (!digitalSignature || digitalSignature.trim() === '') {
    return false;
  }
  
  // デジタル署名が無効な場合は内容の整合性も無効
  if (digitalSignature.startsWith('INVALID:')) {
    return false;
  }
  
  // 有効な署名パターンの場合は内容の整合性も有効
  const validSignaturePatterns = [
    /^valid_signature_string$/,
    /^mext_digital_signature_\d{4}$/,
    /^SHA256:[a-f0-9]+$/
  ];
  
  return validSignaturePatterns.some(pattern => pattern.test(digitalSignature));
}

function checkValidityPeriod(receivedTimestamp: string): boolean {
  if (!receivedTimestamp) {
    return false;
  }
  
  try {
    const receivedDate = new Date(receivedTimestamp);
    const now = new Date();
    
    // 受信日時が現在時刻より未来でなく、過去1年以内であれば有効
    return receivedDate <= now && (now.getTime() - receivedDate.getTime()) <= 365 * 24 * 60 * 60 * 1000;
  } catch {
    return false;
  }
}

export function validateLegalNotificationAuthenticity(
  notificationContent: string,
  senderInfo: any,
  digitalSignature: string,
  receivedTimestamp: string
): { isAuthentic: boolean; isValid: boolean; verificationDetails: VerificationDetails; canProceed: boolean } {
  // 制約チェック
  if (!notificationContent || notificationContent.length < 10) {
    throw new Error("法令改正通知の内容が不正です。正しい通知内容を確認してください。");
  }
  
  if (!digitalSignature || digitalSignature.trim() === '') {
    throw new Error("デジタル署名が見つかりません。文部科学省からの正式な通知であることを確認してください。");
  }
  
  // 送信者情報の検証
  if (!senderInfo || typeof senderInfo !== 'object') {
    throw new Error("送信者の認証情報が不正です。文部科学省からの公式通知であることを確認してください。");
  }
  
  // 送信者情報が不完全な場合のチェック
  if (senderInfo.senderId !== undefined && senderInfo.certificateId !== undefined && senderInfo.authDomain !== undefined) {
    if (senderInfo.senderId === '' && senderInfo.certificateId === '' && senderInfo.authDomain === '') {
      throw new Error("送信者の認証情報が不正です。文部科学省からの公式通知であることを確認してください。");
    }
  }
  
  if (senderInfo.organization === '不明' && senderInfo.verified === false) {
    throw new Error("法令改正通知の内容が不正です。正しい通知内容を確認してください。");
  }
  
  // 擬似コードに従った実装
  const senderValid = verifySenderAuthentication(senderInfo);
  const signatureValid = verifyDigitalSignature(digitalSignature, notificationContent);
  const contentIntact = verifyContentIntegrity(notificationContent, digitalSignature);
  const withinValidPeriod = checkValidityPeriod(receivedTimestamp);
  
  const isAuthentic = senderValid && signatureValid && contentIntact;
  const isValid = isAuthentic && withinValidPeriod;
  const canProceed = isAuthentic && isValid;
  
  return {
    isAuthentic,
    isValid,
    verificationDetails: {
      senderValid,
      signatureValid,
      contentIntact,
      withinValidPeriod
    },
    canProceed
  };
}

export function approveRequirementChange(
  changeRequirements: string,
  impactAnalysis: string,
  directorAuthority: string,
  complianceRisk: number
): { approved: boolean; approvalComment: string; nextAction: string; urgencyLevel: string } {
  // 入力検証
  if (!changeRequirements || changeRequirements.length < 10) {
    throw new Error("変更要件の内容が不十分です。具体的な変更内容を記載してください。");
  }
  
  if (!impactAnalysis) {
    throw new Error("影響分析が完了していません。承認判定に必要な分析結果を確認してください。");
  }

  // 業務ロジック
  const isMoeRelated = changeRequirements.includes("補助金") || changeRequirements.includes("文部科学省");
  const withinAuthority = impactAnalysis.length <= 1000 && directorAuthority === "standard";
  const highRisk = complianceRisk >= 8;

  if (highRisk) {
    return {
      approved: true,
      approvalComment: "法令違反リスク回避のため緊急承認",
      nextAction: "即座に文書分類基準を更新",
      urgencyLevel: "緊急"
    };
  } else if (withinAuthority && isMoeRelated) {
    return {
      approved: true,
      approvalComment: "通常承認",
      nextAction: "文書分類基準の更新を実施",
      urgencyLevel: "通常"
    };
  } else {
    return {
      approved: false,
      approvalComment: "理事会承認が必要",
      nextAction: "理事会への上申準備",
      urgencyLevel: "保留"
    };
  }
}

interface ApprovedChangeRequirement {
  documentType: string;
  newRequirement: string;
}

interface ProcessingRouteMapping {
  documentType: string;
  route: string;
}

function identifyAffectedDocumentTypesInternal(approvedChanges: ApprovedChangeRequirement[]): string[] {
  return approvedChanges.map(change => change.documentType);
}

function evaluateSubsidyRelevanceInternal(docType: string, approvedChanges: ApprovedChangeRequirement[]): boolean {
  return docType.includes('補助金') || docType.includes('助成');
}

function checkMoeRequirementInternal(docType: string, approvedChanges: ApprovedChangeRequirement[]): boolean {
  const change = approvedChanges.find(c => c.documentType === docType);
  return change?.newRequirement === '紙保管必須';
}

function countExistingDocumentsInternal(docType: string): number {
  return 1; // 各文書タイプにつき1件として計算
}

function createRouteMappingInternal(updatedRules: DocumentClassificationRule[]): ProcessingRouteMapping[] {
  return updatedRules.map(rule => ({
    documentType: rule.documentType,
    route: rule.processingRoute
  }));
}

export function updateDocumentClassificationStandards(
  approvedChanges: any[],
  currentClassificationRules: DocumentClassificationRule[],
  effectiveDate: Date
): {
  updatedRules: DocumentClassificationRule[];
  affectedDocumentCount: number;
  newProcessingRoutes: any;
  applicationStartDate: Date;
} {
  if (!approvedChanges || approvedChanges.length === 0) {
    throw new Error("法令改正に伴う変更要件が正しく承認されていません。事務局長による承認を確認してください。");
  }

  const affectedDocumentTypes = identifyAffectedDocumentTypesInternal(approvedChanges);
  const updatedRules: DocumentClassificationRule[] = [];
  let affectedCount = 0;

  for (const docType of affectedDocumentTypes) {
    const subsidyRelated = evaluateSubsidyRelevanceInternal(docType, approvedChanges);
    const paperRequired = subsidyRelated && checkMoeRequirementInternal(docType, approvedChanges);
    const processingRoute = paperRequired ? "hybrid" : "electronic";
    
    updatedRules.push({
      documentType: docType,
      processingRoute,
      paperStorageRequired: paperRequired
    });
    
    affectedCount += countExistingDocumentsInternal(docType);
  }

  return {
    updatedRules,
    affectedDocumentCount: affectedCount,
    newProcessingRoutes: createRouteMappingInternal(updatedRules),
    applicationStartDate: effectiveDate
  };
}

export function determineLegalChangeProcessingPriority(
  urgencyLevel: string,
  impactScope: string,
  affectedDocumentTypes: string[],
  currentProcessingLoad: number
): { priority: string; scheduleDays: number; processingOrder: number; notificationLevel: string } {
  // 緊急度レベルの検証
  if (!["即日対応", "1週間以内", "1ヶ月以内"].includes(urgencyLevel)) {
    throw new Error("緊急度レベルは「即日対応」「1週間以内」「1ヶ月以内」のいずれかを指定してください");
  }

  // 影響範囲の検証
  if (!["全学", "特定部署", "特定業務"].includes(impactScope)) {
    throw new Error("影響範囲は「全学」「特定部署」「特定業務」のいずれかを指定してください");
  }

  // 処理負荷レベルのクランプ
  const clampedProcessingLoad = Math.max(0, Math.min(100, currentProcessingLoad));

  let basePriority = 0;
  if (urgencyLevel === "即日対応") {
    basePriority = 4;
  } else if (urgencyLevel === "1週間以内") {
    basePriority = 3;
  } else {
    basePriority = 2;
  }

  if (impactScope === "全学") {
    basePriority += 1;
  } else if (impactScope === "特定業務") {
    basePriority -= 1;
  }

  if (affectedDocumentTypes.includes("補助金申請書")) {
    basePriority += 1;
  }

  let scheduleDays = basePriority >= 4 ? 1 : basePriority >= 3 ? 7 : 30;
  if (clampedProcessingLoad > 80 && basePriority < 4) {
    scheduleDays *= 1.5;
  }

  const priority = basePriority >= 4 ? "最優先" : basePriority >= 3 ? "高優先" : basePriority >= 2 ? "通常" : "低優先";
  const processingOrder = 5 - basePriority;
  const notificationLevel = basePriority >= 4 ? "緊急" : basePriority >= 3 ? "重要" : "通常";

  return { priority, scheduleDays, processingOrder, notificationLevel };
}

export function ensureBusinessContinuityDuringSystemUpdate(
  updateScope: string,
  activeApplications: number,
  estimatedUpdateDuration: number,
  criticalDeadlines: string[]
): { continuityPlan: string; temporaryRoutes: string[]; rollbackProcedure: string; communicationPlan: string } {
  // 入力値の検証
  if (activeApplications < 0) {
    throw new Error("現在の申請状況を確認できないため、安全な更新計画を立てることができません。システム管理者にお問い合わせください。");
  }
  
  if (estimatedUpdateDuration <= 0) {
    throw new Error("更新作業の所要時間を入力してください。業務継続計画の策定に必要です。");
  }
  
  if (!updateScope) {
    console.warn("影響範囲の詳細が不明な項目があります。より安全な更新計画のため、詳細調査をお勧めします。");
  }

  // 業務への影響度を評価
  const impactLevel = activeApplications > 50 || criticalDeadlines.length > 0 ? "high" : "low";
  
  // 段階的更新が必要かどうかを判定
  const requiresStaging = estimatedUpdateDuration > 120;
  
  // 一時的な代替処理ルートを準備
  const temporaryRoutes: string[] = [];
  
  if (updateScope.includes("documentClassification")) {
    temporaryRoutes.push("manual_paper_route");
  }
  
  if (impactLevel === "high") {
    temporaryRoutes.push("emergency_manual_route");
  }
  
  // 業務継続計画を決定
  const continuityPlan = requiresStaging ? "staged_update" : "direct_update";
  
  // 復旧手順を準備
  const rollbackProcedure = "immediate_rollback_available";
  
  // 関係者への連絡計画を決定
  const communicationPlan = impactLevel === "high" ? "advance_notification_required" : "standard_notification";
  
  return {
    continuityPlan,
    temporaryRoutes,
    rollbackProcedure,
    communicationPlan
  };
}

function getApproverByStage(documentType: string, currentApprovalStage: string) {
  const approverMap: { [key: string]: { id: string } } = {
    '部長承認': { id: 'MGR-001' },
    '課長承認': { id: 'MGR-002' },
    '理事承認': { id: 'MGR-003' }
  };
  return approverMap[currentApprovalStage];
}

function findSubstituteApprover(documentType: string, currentApprovalStage: string) {
  const substituteMap: { [key: string]: { id: string } | null } = {
    '課長承認': { id: 'SUB-001' },
    '理事承認': null
  };
  return substituteMap[currentApprovalStage] || null;
}

function findSuperiorApprover(documentType: string, currentApprovalStage: string) {
  const superiorMap: { [key: string]: { id: string } } = {
    '理事承認': { id: 'DIR-001' }
  };
  return superiorMap[currentApprovalStage] || { id: 'DIR-001' };
}

export function identifyNotificationRecipient(
  applicationId: string,
  documentType: string,
  currentApprovalStage: string,
  assignedApproverId: string,
  approverAvailability: boolean
): { recipientId: string; recipientType: string; notificationMethod: string; escalationRequired: boolean } {
  if (!applicationId || applicationId.trim() === '') {
    throw new Error('催促対象の申請案件が特定できません。正しい申請番号を確認してください。');
  }

  if (!currentApprovalStage || currentApprovalStage.trim() === '') {
    throw new Error('承認フローの現在段階を特定できません。申請状況を確認してください。');
  }

  const primaryApprover = getApproverByStage(documentType, currentApprovalStage);
  
  let recipientId: string;
  let recipientType: string;
  let escalationRequired: boolean;

  if (approverAvailability && assignedApproverId === primaryApprover?.id) {
    recipientId = assignedApproverId;
    recipientType = "primary_approver";
    escalationRequired = false;
  } else {
    const substitute = findSubstituteApprover(documentType, currentApprovalStage);
    if (substitute != null) {
      recipientId = substitute.id;
      recipientType = "substitute_approver";
      escalationRequired = false;
    } else {
      const superior = findSuperiorApprover(documentType, currentApprovalStage);
      if (!superior || (!primaryApprover && !assignedApproverId)) {
        throw new Error('催促通知の送信先を特定できません。システム管理者にお問い合わせください。');
      }
      recipientId = superior.id;
      recipientType = "superior_approver";
      escalationRequired = true;
    }
  }

  const isHighPriority = documentType.includes("補助金") || documentType.includes("subsidy") || documentType.includes("grant");
  const notificationMethod = isHighPriority ? "urgent_contact" : "email";

  return { recipientId, recipientType, notificationMethod, escalationRequired };
}

function extractAffectedRegulations(regulationChangeContent: string, affectedRegulationTypes: string[]): string[] {
  if (!regulationChangeContent.trim()) {
    return [];
  }
  
  return affectedRegulationTypes.filter(regType => 
    regulationChangeContent.includes(regType) || 
    regulationChangeContent.includes('補助金') && regType.includes('補助金')
  );
}

function isRegulationMatch(docRegulationCategory: string | undefined, affectedRegulations: string[]): boolean {
  if (!docRegulationCategory) return false;
  return affectedRegulations.some(reg => 
    docRegulationCategory.includes(reg) || reg.includes(docRegulationCategory)
  );
}

function determineNewProcessingRouteInternal(docType: DocumentClassificationRule, regulationChangeContent: string): string {
  const content = regulationChangeContent.toLowerCase();
  
  if (content.includes('電子保存のみで可') || content.includes('電子のみ')) {
    return 'electronic';
  }
  
  if (content.includes('紙保管必須') || content.includes('書面保存')) {
    return 'paper';
  }
  
  // 研究費申請書や設備導入申請書が明示的に電子保存のみと記載されている場合
  if ((docType.typeName?.includes('研究費') || docType.typeName?.includes('設備導入')) && 
      content.includes('電子保存のみで可')) {
    return 'electronic';
  }
  
  return docType.storageRequirement || docType.processingRoute || 'hybrid';
}

export function analyzeRegulationImpactScope(
  regulationChangeContent: string, 
  affectedRegulationTypes: string[], 
  currentDocumentTypes: DocumentClassificationRule[]
): { 
  affectedDocumentTypes: string[]; 
  processingRouteChanges: ProcessingRouteChange[]; 
  impactLevel: string; 
  changeRequiredCount: number 
} {
  if (!regulationChangeContent || !regulationChangeContent.trim()) {
    throw new Error("法令改正の変更内容が正しく取得できていません。改正通知の受信処理を確認してください。");
  }

  if (!currentDocumentTypes) {
    throw new Error("システムに登録されている文書種別の情報を取得できません。データベース接続を確認してください。");
  }

  const affectedRegulations = extractAffectedRegulations(regulationChangeContent, affectedRegulationTypes);
  const affectedTypes: string[] = [];
  const routeChanges: ProcessingRouteChange[] = [];

  for (const docType of currentDocumentTypes) {
    if (isRegulationMatch(docType.regulationCategory, affectedRegulations)) {
      if (docType.typeName) {
        affectedTypes.push(docType.typeName);
      }
      
      const currentRoute = docType.storageRequirement || docType.processingRoute || 'hybrid';
      const newRoute = determineNewProcessingRouteInternal(docType, regulationChangeContent);
      
      if (currentRoute !== newRoute) {
        routeChanges.push({ 
          documentType: docType.typeName || docType.documentType, 
          oldRoute: currentRoute, 
          newRoute: newRoute 
        });
      }
    }
  }

  if (affectedTypes.length > 100) {
    console.warn("影響範囲が非常に広範囲です。段階的な対応計画の策定を推奨します。");
  }

  const impactLevel = routeChanges.length === 0 ? "軽微" : routeChanges.length <= 5 ? "中程度" : "重大";

  return { 
    affectedDocumentTypes: affectedTypes, 
    processingRouteChanges: routeChanges, 
    impactLevel: impactLevel, 
    changeRequiredCount: routeChanges.length 
  };
}

export function determineDirectorApprovalRequired(
  complianceCheckResult: any,
  applicationAmount: number,
  documentRiskLevel: string,
  subsidyCategory: string
): { approvalRequired: boolean; approvalReason: string; nextProcessStep: string; riskAssessment: string } {
  // 制約チェック
  if (complianceCheckResult === null || complianceCheckResult === undefined) {
    throw new Error("適合性チェックが完了していません。先に適合性確認を実施してください");
  }

  if (applicationAmount < 0) {
    throw new Error("申請金額は0以上の値を入力してください");
  }

  if (!documentRiskLevel) {
    console.warn("法令リスクレベルが設定されていません。標準リスクとして処理します");
  }

  // 承認要否判定フラグ
  const highAmountFlag = applicationAmount >= 10000000;
  const highRiskFlag = documentRiskLevel === "高" || documentRiskLevel === "中";
  const prioritySubsidyFlag = subsidyCategory === "重点施策関連";
  const complianceIssueFlag = complianceCheckResult.hasIssues;

  const approvalRequired = highAmountFlag || highRiskFlag || prioritySubsidyFlag || complianceIssueFlag;

  // 承認理由の決定
  let approvalReason = "";
  if (highAmountFlag) {
    approvalReason = "高額申請のため";
  } else if (highRiskFlag) {
    approvalReason = "法令リスクが高いため";
  } else if (prioritySubsidyFlag) {
    approvalReason = "重点施策関連のため";
  } else if (complianceIssueFlag) {
    approvalReason = "適合性に疑義があるため";
  } else {
    approvalReason = "自動承認条件を満たすため";
  }

  // 次処理ステップの決定
  const nextProcessStep = approvalRequired ? "事務局長承認待ち" : "申請資料作成";

  // リスク評価の決定
  const riskAssessment = highRiskFlag ? "要注意" : "標準";

  return {
    approvalRequired,
    approvalReason,
    nextProcessStep,
    riskAssessment
  };
}

function isInMigrationScope(document: any, migrationScope: string): boolean {
  if (migrationScope === "subsidy_and_research_documents") {
    return document.type === "補助金申請書" || document.type === "研究費申請書";
  }
  if (migrationScope === "all") {
    return true;
  }
  return false;
}

function applyNewClassificationRules(document: any, rules: DocumentClassificationRule[]): DocumentClassificationRule | null {
  return rules.find(rule => rule.documentType === document.type) || null;
}

function updateDocumentRoute(documentId: string, newClassification: DocumentClassificationRule): void {
  // 実際の更新処理（この実装では戻り値に影響しないため空実装）
}

export function migrateExistingDataToNewClassification(
  newClassificationRules: DocumentClassificationRule[], 
  existingDocuments: any[], 
  migrationScope: string
): { migratedCount: number; skippedCount: number; errorCount: number; updatedRoutes: ProcessingRouteChange[] } {
  if (newClassificationRules.length === 0) {
    throw new Error("法令改正に基づく新しい分類基準が設定されていません。分類基準を確認してください。");
  }

  if (!existingDocuments) {
    throw new Error("既存の申請書類データにアクセスできません。システム管理者に連絡してください。");
  }

  const targetDocuments = existingDocuments.filter(doc => isInMigrationScope(doc, migrationScope));
  
  let migratedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;
  const updatedRoutes: ProcessingRouteChange[] = [];

  for (const document of targetDocuments) {
    try {
      const newClassification = applyNewClassificationRules(document, newClassificationRules);
      if (newClassification && newClassification.processingRoute !== document.current_processing_route) {
        updateDocumentRoute(document.id, newClassification);
        updatedRoutes.push({
          documentType: document.type,
          oldRoute: document.current_processing_route,
          newRoute: newClassification.processingRoute
        });
        migratedCount++;
      } else {
        skippedCount++;
      }
    } catch (error) {
      errorCount++;
    }
  }

  return { migratedCount, skippedCount, errorCount, updatedRoutes };
}
