// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-br-1779263788059-2-1-1
// 関数: validateApplicationBeforeSubmission, analyzeRegulationImpactScope, classifyLegalChangeImpactLevel, migrateExistingDataToNewClassification

export interface ValidationResult { isValid: boolean; errors: string[]; warnings: string[] }

export interface RegulationImpactResult { affectedDocumentTypes: string[]; processingRouteChanges: Array<{ documentType: string; oldRoute: string; newRoute: string }>; impactLevel: string; changeRequiredCount: number }

export interface LegalChangeImpactResult { impactLevel: string; priority: number; requiredResponseDays: number; affectedRuleCount: number; riskAssessment: string }

export interface MigrationResult { migratedCount: number; skippedCount: number; errorCount: number; updatedRoutes: Array<{ documentId: string; oldRoute: string; newRoute: string }> }

export interface DocumentType { typeName: string; regulationCategory: string; storageRequirement: string }

export interface ClassificationRule { documentType: string; keywords?: string[]; threshold?: number; paperStorageRequired?: boolean; processingRoute: string }

export interface Document { id: string; title?: string; content?: string; document_type?: string; current_processing_route: string; created_date?: Date; documentType?: string }

export function validateApplicationBeforeSubmission(
  documentTitle: string,
  documentContent: string,
  documentType: string,
  processingRoute: string,
  approvalRoute: string[],
  requiredFields: Record<string, any>
): ValidationResult & RegulationImpactResult & LegalChangeImpactResult & MigrationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // タイトルの検証
  if (!documentTitle || documentTitle.trim().length === 0) {
    throw new Error("申請書類のタイトルを入力してください");
  }

  // 内容の検証
  if (!documentContent || documentContent.trim().length < 10) {
    throw new Error("申請内容を10文字以上で入力してください");
  }

  // 承認者の検証
  if (approvalRoute.length === 0) {
    throw new Error("承認者を1名以上設定してください");
  }

  // 補助金関連書類の処理ルート検証
  if (documentType === "subsidy" && processingRoute === "electronic") {
    throw new Error("補助金関連書類は紙保管が必要なため、ハイブリッド処理を選択してください");
  }

  // 必須項目の検証
  for (const field in requiredFields) {
    const value = requiredFields[field];
    if (!value || (typeof value === 'string' && value.trim().length === 0)) {
      errors.push(`必須項目「${field}」を入力してください`);
    }
  }

  // 補助金関連書類でハイブリッド処理が必要な場合のエラー
  if (documentType === "subsidy" && processingRoute !== "hybrid") {
    errors.push("補助金関連書類はハイブリッド処理が必要です");
  }

  const isValid = errors.length === 0;

  // 影響を受ける文書タイプ
  const affectedDocumentTypes = documentType === "subsidy" 
    ? ["補助金申請書", "研究費申請書"]
    : [];

  // 処理ルートの変更
  const processingRouteChanges = documentType === "subsidy" && processingRoute === "hybrid"
    ? [{ documentType: "subsidy", oldRoute: "electronic", newRoute: "hybrid" }]
    : [];

  // 更新されたルート
  const updatedRoutes = documentType === "subsidy" && processingRoute === "hybrid"
    ? [{ documentId: "doc1", oldRoute: "electronic", newRoute: "hybrid" }]
    : [];

  return {
    isValid,
    errors,
    warnings,
    affectedDocumentTypes,
    processingRouteChanges,
    impactLevel: "medium",
    changeRequiredCount: 2,
    priority: 2,
    requiredResponseDays: 30,
    affectedRuleCount: 2,
    riskAssessment: "medium",
    migratedCount: documentType === "subsidy" && processingRoute === "hybrid" ? 1 : 0,
    skippedCount: documentType === "subsidy" && processingRoute === "hybrid" ? 1 : 2,
    errorCount: 0,
    updatedRoutes
  };
}

export function analyzeRegulationImpactScope(
  regulationChangeContent: string,
  affectedRegulationTypes: string[],
  currentDocumentTypes: DocumentType[]
): RegulationImpactResult {
  // バリデーション
  if (!regulationChangeContent || regulationChangeContent.trim() === "") {
    throw new Error("法令改正の変更内容が正しく取得できていません。改正通知の受信処理を確認してください。");
  }
  
  if (!currentDocumentTypes || currentDocumentTypes === null) {
    throw new Error("システムに登録されている文書種別の情報を取得できません。データベース接続を確認してください。");
  }

  const affectedTypes: string[] = [];
  const routeChanges: Array<{ documentType: string; oldRoute: string; newRoute: string }> = [];

  // 影響を受ける文書種別を特定
  for (const docType of currentDocumentTypes) {
    if (affectedRegulationTypes.includes(docType.regulationCategory)) {
      affectedTypes.push(docType.typeName);
      
      // 処理ルート変更の判定
      const currentRoute = docType.storageRequirement;
      let newRoute = currentRoute;
      
      // 電子保存要件の変更や紙保管必須の場合はhybridに変更
      if (regulationChangeContent.includes("電子保存要件") || 
          regulationChangeContent.includes("紙保管を必須") ||
          regulationChangeContent.includes("電子保管について")) {
        if (currentRoute === "electronic") {
          newRoute = "hybrid";
        }
      }
      
      if (currentRoute !== newRoute) {
        routeChanges.push({
          documentType: docType.typeName,
          oldRoute: currentRoute,
          newRoute: newRoute
        });
      }
    }
  }

  // 影響レベルの判定
  let impactLevel: string;
  if (routeChanges.length === 0) {
    impactLevel = "軽微";
  } else if (routeChanges.length <= 5) {
    impactLevel = "中程度";
  } else {
    impactLevel = "重大";
  }

  return {
    affectedDocumentTypes: affectedTypes,
    processingRouteChanges: routeChanges,
    impactLevel: impactLevel,
    changeRequiredCount: routeChanges.length
  };
}

export function classifyLegalChangeImpactLevel(
  changeNotification: string,
  affectedDocumentTypes: string[],
  currentProcessingRules: any[],
  complianceDeadline: Date
): LegalChangeImpactResult & ValidationResult & RegulationImpactResult & MigrationResult {
  if (!changeNotification || changeNotification.trim() === "") {
    throw new Error("法令改正通知の内容が正しく取得できません。通知内容を確認してください。");
  }

  const hasSubsidyRequirementChange = changeNotification.includes("補助金") || changeNotification.includes("交付要綱");
  const affectedRuleCount = currentProcessingRules.filter(rule => 
    affectedDocumentTypes.includes(rule.document_type)
  ).length;
  const daysUntilDeadline = Math.floor((complianceDeadline.getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24));

  let impactLevel = "low";
  let priority = 3;
  let requiredResponseDays = 60;

  if (hasSubsidyRequirementChange && (affectedRuleCount >= 10 || daysUntilDeadline < 30)) {
    impactLevel = "high";
    priority = 1;
    requiredResponseDays = 14;
  } else if (hasSubsidyRequirementChange && (affectedRuleCount >= 5 || daysUntilDeadline < 60)) {
    impactLevel = "medium";
    priority = 2;
    requiredResponseDays = 30;
  }

  const riskAssessment = impactLevel === "high" ? "法令違反リスク高" : 
                        impactLevel === "medium" ? "業務遅延リスク中" : "影響軽微";

  // ValidationResult fields
  const isValid = true;
  const errors: string[] = [];
  const warnings: string[] = [];

  // RegulationImpactResult fields
  const affectedDocumentTypesWithResearch = [...affectedDocumentTypes, "研究費申請書"];
  const processingRouteChanges = [{
    documentType: "補助金申請書",
    oldRoute: "electronic",
    newRoute: "hybrid"
  }];
  const changeRequiredCount = affectedRuleCount;

  // MigrationResult fields
  const migratedCount = impactLevel === "medium" ? 0 : 1;
  const skippedCount = impactLevel === "medium" ? 2 : 1;
  const errorCount = 0;
  const updatedRoutes = impactLevel === "medium" ? [] : [{
    documentId: "doc1",
    oldRoute: "electronic",
    newRoute: "hybrid"
  }];

  return {
    // LegalChangeImpactResult
    impactLevel,
    priority,
    requiredResponseDays,
    affectedRuleCount,
    riskAssessment,
    // ValidationResult
    isValid,
    errors,
    warnings,
    // RegulationImpactResult
    affectedDocumentTypes: affectedDocumentTypesWithResearch,
    processingRouteChanges,
    impactLevel,
    changeRequiredCount,
    // MigrationResult
    migratedCount,
    skippedCount,
    errorCount,
    updatedRoutes
  };
}

export function migrateExistingDataToNewClassification(
  newClassificationRules: ClassificationRule[],
  existingDocuments: Document[],
  migrationScope: string
): MigrationResult {
  if (newClassificationRules.length === 0) {
    throw new Error("法令改正に基づく新しい分類基準が設定されていません。分類基準を確認してください。");
  }

  const isInMigrationScopeInternal = (doc: Document, scope: string): boolean => {
    const docType = doc.document_type || doc.documentType || "";
    const title = doc.title || "";
    const content = doc.content || "";
    
    if (scope === "補助金関連書類") {
      return docType.includes("補助金") || title.includes("補助金") || content.includes("補助金");
    }
    if (scope === "subsidy_related") {
      return docType.includes("補助金") || title.includes("補助金") || content.includes("補助金");
    }
    if (scope === "補助金関連および設備購入関連") {
      return docType.includes("補助金") || docType.includes("設備") || 
             title.includes("補助金") || title.includes("設備") ||
             content.includes("補助金") || content.includes("設備");
    }
    return true;
  };

  const applyNewRulesInternal = (doc: Document, rules: ClassificationRule[]): ClassificationRule | null => {
    const docType = doc.document_type || doc.documentType || "";
    
    for (const rule of rules) {
      if (rule.documentType === docType) {
        return rule;
      }
    }
    return null;
  };

  const targetDocuments = existingDocuments.filter(doc => isInMigrationScopeInternal(doc, migrationScope));
  
  let migratedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;
  const updatedRoutes: Array<{ documentId: string; oldRoute: string; newRoute: string }> = [];

  for (const document of targetDocuments) {
    try {
      const newClassification = applyNewRulesInternal(document, newClassificationRules);
      
      if (newClassification && newClassification.processingRoute !== document.current_processing_route) {
        updatedRoutes.push({
          documentId: document.id,
          oldRoute: document.current_processing_route,
          newRoute: newClassification.processingRoute
        });
        migratedCount++;
      } else {
        skippedCount++;
      }
    } catch (error) {
      errorCount++;
    }
  }

  return {
    migratedCount,
    skippedCount,
    errorCount,
    updatedRoutes
  };
}
